/**
 * The demo video — recorded by driving the real product, not by narrating over it.
 *
 * ## Why this is scripted rather than screen-recorded by hand
 *
 * A hand-recorded take is a claim the viewer has to trust: they see a number appear and have to
 * believe it came from the software rather than from a good take. This entry's whole argument is
 * that you do not have to trust us — so the one artefact that shows the argument had better be made
 * the same way the argument is. Every frame here comes from the built app, running against the real
 * API, doing the thing on camera. Nothing is staged, and re-running this produces the same film.
 *
 * That is also why it follows `README.md`'s own sixty-second path in the same order: the README, the
 * app and the video cannot drift apart if the video is generated by walking the README.
 *
 * ## The shape of the recording
 *
 * A phone, because this is a Mini App and every game of it is played on one. Playwright's
 * `recordVideo` only renders sharply when the video size **equals** the viewport at
 * `deviceScaleFactor: 1` — a larger scale factor letterboxes the page into the top-left corner of
 * the canvas — so the capture is a native 430×932 and the finishing pass upscales it and sets it on
 * a backdrop. That ffmpeg command is printed at the end rather than run from here: on Windows, node
 * spawning ffmpeg with a `-vf` filter string fails on cmd.exe quoting, and a transcode that dies
 * after the capture has been thrown away is the one failure mode worth designing out.
 *
 * Headless Chromium draws no pointer, so a video of it looks like a ghost using the app. The init
 * script below draws a finger — a soft dot that moves and ripples on every tap — because the point
 * of the film is to show a person using this, and an invisible one shows nothing.
 *
 *   node --experimental-strip-types scripts/demo-video.mjs
 */
import { mkdirSync, writeFileSync, readdirSync, renameSync } from 'node:fs';
import { chromium } from 'playwright';
import { startApp } from './harness.mjs';

const OUT = 'demo';
const WIDTH = 430;
const HEIGHT = 932;

mkdirSync(OUT, { recursive: true });

/*
 * Its own ports. `look.mjs` holds 4174/8788/8790 and `judge-mode.mjs` 4175/8791/8792, so a recording
 * can be made while either of them is running without the three fighting over a socket.
 */
const { base: BASE } = await startApp({ port: 4176, apiPort: 8793, stubNodePort: 8794 });

/**
 * A visible finger, drawn in the page.
 *
 * Headless Chromium composites no cursor into the recording, so without this the app appears to
 * operate itself. The dot is deliberately soft and semi-transparent — a hard arrow reads as a mouse,
 * and this is a touch app — and each tap leaves a ripple so the viewer can see *when* the tap landed
 * rather than inferring it from what changed afterwards.
 */
const FINGER = `(() => {
  const dot = document.createElement('div');
  dot.style.cssText =
    'position:fixed;left:0;top:0;width:34px;height:34px;margin:-17px 0 0 -17px;border-radius:50%;' +
    'background:rgba(20,20,20,.28);border:2px solid rgba(255,255,255,.75);pointer-events:none;' +
    'z-index:2147483647;transition:transform .05s linear;will-change:transform';
  const place = (x, y) => { dot.style.transform = 'translate(' + x + 'px,' + y + 'px)'; };
  place(-100, -100);
  const attach = () => document.body && !dot.isConnected && document.body.append(dot);
  attach();
  document.addEventListener('DOMContentLoaded', attach);
  window.__finger = (x, y) => { attach(); place(x, y); };
  window.__ripple = (x, y) => {
    attach();
    const ring = document.createElement('div');
    ring.style.cssText =
      'position:fixed;left:' + x + 'px;top:' + y + 'px;width:12px;height:12px;margin:-6px 0 0 -6px;' +
      'border-radius:50%;border:2px solid rgba(20,20,20,.55);pointer-events:none;z-index:2147483646';
    document.body.append(ring);
    ring.animate(
      [{ transform: 'scale(1)', opacity: 0.9 }, { transform: 'scale(4.5)', opacity: 0 }],
      { duration: 480, easing: 'ease-out' },
    ).onfinish = () => ring.remove();
  };
})()`;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const browser = await chromium.launch();
const context = await browser.newContext({
  viewport: { width: WIDTH, height: HEIGHT },
  deviceScaleFactor: 1,
  hasTouch: true,
  isMobile: true,
  recordVideo: { dir: OUT, size: { width: WIDTH, height: HEIGHT } },
});
await context.addInitScript(FINGER);
const page = await context.newPage();

/**
 * What the witness serves, captured as the app receives it.
 *
 * A puzzle id is `<fen>|<uci moves>`, so this is the solution to the run about to be played — which
 * is how the finger can solve it on camera at a human pace instead of guessing. The puzzles are
 * still chosen by the server and the card is still countersigned by it; only the hands are ours.
 */
let served = null;
page.on('response', async (response) => {
  if (!response.url().includes('/api/puzzles/session')) return;
  try {
    const body = await response.json();
    if (Array.isArray(body?.puzzles)) served = body.puzzles.map((one) => one.id);
  } catch {
    // Not the response this is looking for.
  }
});

let at = { x: WIDTH / 2, y: HEIGHT + 60 };

/** Move the drawn finger along an eased path, so it reads as a hand rather than a teleport. */
async function moveTo(x, y, ms = 520) {
  const from = { ...at };
  const steps = Math.max(8, Math.round(ms / 16));
  for (let step = 1; step <= steps; step++) {
    const p = step / steps;
    // Ease in and out. A linear glide is the single thing that makes a scripted demo look scripted.
    const eased = p < 0.5 ? 2 * p * p : 1 - (-2 * p + 2) ** 2 / 2;
    const nx = from.x + (x - from.x) * eased;
    const ny = from.y + (y - from.y) * eased;
    await page.evaluate(([px, py]) => window.__finger?.(px, py), [nx, ny]);
    await sleep(ms / steps);
  }
  at = { x, y };
}

/** Tap something the way a thumb would: move to it, ripple, then send a real tap. */
async function tap(target, { settle = 420 } = {}) {
  const locator = typeof target === 'string' ? page.locator(target).first() : target;
  await locator.waitFor({ state: 'visible', timeout: 20_000 });
  const box = await locator.boundingBox();
  if (!box) throw new Error('nothing to tap');
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  await moveTo(x, y);
  await page.evaluate(([px, py]) => window.__ripple?.(px, py), [x, y]);
  await locator.tap();
  await sleep(settle);
}

/** Hold still on something worth reading. Signature moments need screen time, not a glimpse. */
const beat = (ms) => sleep(ms);

/**
 * Scroll something into the middle of the frame, at reading speed.
 *
 * The verdict a Recompute produces renders *below* the button that produced it, so on a phone the
 * most important sentence in the film appeared off the bottom of the screen — the tap landed, the
 * answer arrived, and the camera was pointed at the button. `scrollIntoViewIfNeeded` only nudges an
 * element to the nearest edge, which is barely better. This eases it to the centre and leaves it
 * there.
 */
async function bringIntoView(selector, ms = 1100) {
  const target = page.locator(selector).first();
  if (!(await target.count())) return;
  const to = await target.evaluate((node) => {
    const box = node.getBoundingClientRect();
    return window.scrollY + box.top + box.height / 2 - window.innerHeight / 2;
  });
  const from = await page.evaluate(() => window.scrollY);
  const steps = Math.max(10, Math.round(ms / 16));
  for (let step = 1; step <= steps; step++) {
    const p = step / steps;
    const eased = p < 0.5 ? 2 * p * p : 1 - (-2 * p + 2) ** 2 / 2;
    await page.evaluate((y) => window.scrollTo(0, y), from + (to - from) * eased);
    await sleep(ms / steps);
  }
}

const timeline = [];
const started = Date.now();
const segment = (name) => {
  timeline.push({ name, atMs: Date.now() - started });
  console.log(`  ${((Date.now() - started) / 1000).toFixed(1)}s  ${name}`);
};

console.log(`\nrecording against ${BASE}\n`);

/* ---------------------------------------------------------------- 0:00 a board, immediately */

segment('a board, with nothing asked for');
await page.goto(`${BASE}/?demo=1`, { waitUntil: 'networkidle' });
await page.waitForSelector('.board', { timeout: 30_000 });
await beat(1800);

/*
 * One real move against the real engine.
 *
 * `e2` to `e4` rather than "the first liftable square": the opening move everybody recognises reads
 * instantly, and a video's first three seconds are the only ones some viewers watch.
 */
segment('a move, against a real engine');
await tap('[data-square="e2"]');
await tap('[data-square="e4"]', { settle: 1500 });
await page.waitForSelector('.moves__move', { timeout: 20_000 });
await beat(1600);

/* ---------------------------------------------------------------- 0:15 signing the result */

/*
 * Buttons found by the words on them, not by a test hook.
 *
 * `look.mjs` already presses this exact path by reading the button names out of the README, and it
 * is the right way here too: if a caption ever changes, this film stops recording rather than
 * quietly filming a different product. Resign asks twice — the README was wrong about that once,
 * and a viewer following the video literally would watch nothing happen on the first tap.
 */
segment('resigning, and signing the result');
const resign = page.locator('button:has-text("Resign")').first();
await tap(resign, { settle: 700 });
await tap(resign, { settle: 900 });
await page.waitForSelector('.ending', { state: 'visible', timeout: 40_000 });
await beat(1600);

await tap(page.locator('button:has-text("Sign the result so it counts")').first(), { settle: 1200 });
// The scoresheet is shown in full *before* it is signed. That is the whole claim, so it gets read time.
await page.waitForFunction(() => /see your record/i.test(document.body.textContent ?? ''), { timeout: 30_000 });
await beat(2800);

/* ---------------------------------------------------------------- a rating earned alone */

/*
 * ⭐ The run is solved on camera, and it is why this segment comes *before* the record.
 *
 * The first cut of this film resigned a one-move game and went straight to Recompute, which duly
 * reported "none of them rate, so the rating stays at its starting value". Every word of that was
 * true and it was a terrible demonstration: the hero shot of a product about a rating you own showed
 * a rating that had not moved. A game has to reach ten moves before it rates, and filming twenty
 * taps of chess is not the answer either.
 *
 * A rated puzzle run is: five puzzles, chosen by the server, countersigned by it, and signed by the
 * player — a real rating earned by one person with one wallet, which is the thing this product does
 * that neither Lichess nor Chess.com does. Solving it here means the Recompute a few seconds later
 * has something real to re-derive.
 */
segment('five puzzles, served and countersigned — a rating earned alone');
await page.goto(`${BASE}/puzzles/train?demo=1`, { waitUntil: 'networkidle' });
await page.waitForSelector('.puzzles', { timeout: 20_000 });
await beat(1800);

for (const id of served ?? []) {
  const line = id.split('|')[1].split(' ');
  for (let ply = 1; ply < line.length; ply += 2) {
    // The opponent's reply is played by the app; wait for it rather than guessing at a delay.
    await page
      .waitForFunction(() => !document.querySelector('.puzzles__prompt')?.textContent?.includes('…'), {
        timeout: 10_000,
      })
      .catch(() => {});
    const uci = line[ply];
    await tap(`[data-square="${uci.slice(0, 2)}"]`, { settle: 220 });
    await tap(`[data-square="${uci.slice(2, 4)}"]`, { settle: 420 });

    const picker = page.locator('.promo__choice');
    if (await picker.first().isVisible().catch(() => false)) {
      const order = ['q', 'r', 'n', 'b'];
      await tap(picker.nth(Math.max(0, order.indexOf(uci[4] ?? 'q'))), { settle: 320 });
    }
  }
  await beat(500);
}

await page
  .waitForFunction(() => /run signed/i.test(document.querySelector('.puzzles__prompt')?.textContent ?? ''), {
    timeout: 40_000,
  })
  .catch(() => {});
await bringIntoView('.puzzles__prompt', 800);
// The signed run, and the number it produced. This is the sentence the whole segment exists for.
await beat(3200);

/* ---------------------------------------------------------------- the record, recomputed */

segment('the record, recomputed in this browser');
await page.goto(`${BASE}/?demo=1`, { waitUntil: 'networkidle' });
await page.waitForSelector('.board', { timeout: 20_000 });
await tap(page.locator('.nav__link').filter({ hasText: /^You$/ }).first(), { settle: 1400 });
await page.waitForSelector('.record', { timeout: 20_000 });
await beat(2000);

await tap(page.locator('.record__recompute .btn--primary').first(), { settle: 1200 });
await page.waitForSelector('.record__verdict', { timeout: 30_000 }).catch(() => {});
// The verdict renders below the button. Bring it to the middle of the frame and leave it there —
// this sentence is the reason the product exists, and it had been playing off the bottom edge.
await bringIntoView('.record__verdict');
await beat(4200);

/* ---------------------------------------------------------------- and a tournament */

segment('a tournament, scored by rules a stranger can recompute');
await page.goto(`${BASE}/play?demo=1`, { waitUntil: 'networkidle' });
await page.waitForSelector('.lobby', { timeout: 20_000 });
await beat(900);
await tap('[data-action="hold-tournament"]', { settle: 2600 });
await page.waitForSelector('.tourney', { timeout: 30_000 });
await beat(2800);

segment('end');
await beat(900);

/* ---------------------------------------------------------------- finish */

const video = page.video();
await context.close();
await browser.close();

const raw = video ? await video.path() : null;
let webm = raw;
if (raw) {
  webm = `${OUT}/scoresheet-demo.webm`;
  renameSync(raw, webm);
}

/*
 * The timeline is written *before* anything is transcoded.
 *
 * If the finishing pass fails, the record of what was filmed and when must survive it — otherwise a
 * failed transcode costs the whole take rather than one command.
 */
writeFileSync(
  `${OUT}/timeline.json`,
  `${JSON.stringify({ base: BASE, width: WIDTH, height: HEIGHT, webm, segments: timeline }, null, 2)}\n`,
);

const leftovers = readdirSync(OUT).filter((name) => name.endsWith('.webm') && !name.includes('scoresheet-demo'));
for (const name of leftovers) console.log(`  note: an extra capture is in ${OUT}/${name}`);

console.log(`\nrecorded ${((Date.now() - started) / 1000).toFixed(0)}s to ${webm}`);
console.log('\nfinish it from Git Bash — node spawning ffmpeg with a -vf filter fails on cmd.exe quoting:\n');
console.log(
  `  ffmpeg -y -i ${webm} -c:v libx264 -preset slow -crf 18 -pix_fmt yuv420p \\\n` +
    `    -vf "scale=-2:1080:flags=lanczos,pad=1920:1080:(ow-iw)/2:0:color=0x111110,format=yuv420p" \\\n` +
    `    -movflags +faststart -r 30 ${OUT}/scoresheet-demo.mp4\n`,
);
