/**
 * Vendor the piece set, once, reproducibly.
 *
 * The pieces are **chessnut** by Alexis Luengas, **Apache-2.0** — verified from
 * `LexLuengas/chessnut-pieces`'s own metadata and cross-checked against Lichess's attribution table
 * in `lichess-org/lila`'s `COPYING.md`, both read 6 September 2026.
 *
 * Why not cburnett, which is what everybody reaches for: it is **GPLv2+**, and shipping it to a
 * browser is distribution, which would make an MIT bundle GPL. Most of Lichess's other sets are
 * CC BY-NC-SA — non-commercial, so also out. Of the whole roster only chessnut (Apache-2.0),
 * Maurizio Monge's three (MIT) and rhosgfx (CC0) are usable here at all.
 *
 * The output is committed, so the app has no build-time network dependency and the pieces work
 * offline. Re-run this only to update them:
 *
 *   node scripts/vendor-pieces.mjs
 *
 * Every colour is stripped, so the stylesheet owns them. That turns twelve fixed images into one
 * shape set any theme can colour, and it is what allows both piece colours to be contrast-checked
 * against every board colour rather than hoped about.
 */

import { writeFileSync } from 'node:fs';

const BASE = 'https://raw.githubusercontent.com/LexLuengas/chessnut-pieces/master';
const PIECES = ['P', 'N', 'B', 'R', 'Q', 'K'];

/** Strip everything a browser does not need: the XML declaration, the DOCTYPE, comments, ids. */
function clean(svg) {
  return svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!DOCTYPE[^>]*>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+id="[^"]*"/g, '')
    .replace(/\s+xml:space="[^"]*"/g, '')
    .replace(/\s+version="[^"]*"/g, '')
    .replace(/\s+x="0px"|\s+y="0px"/g, '')
    .replace(/\s+width="[^"]*"|\s+height="[^"]*"/g, '')
    .replace(/\s+enable-background="[^"]*"/g, '')
    .replace(/\s*\n\s*/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

/**
 * Take every colour out, so the stylesheet owns them.
 *
 * The set encodes colour three different ways, which is why substituting hex values one at a time
 * missed most of them: white pieces carry `style="fill:#FFFFFF;stroke:#000000"`, black pieces carry
 * `stroke="#F2F2F2"` as a plain attribute, and a black piece's *body* has no fill at all and relies
 * on SVG defaulting to black.
 *
 * Stripping all three and letting the wrapper element supply `fill` and `stroke` by inheritance
 * turns twelve fixed images into one shape set that any theme can colour — which is what allows
 * both piece colours to be contrast-checked against every board colour rather than hoped about.
 *
 * `fill="none"` and `fill:none` are kept: they are structural, marking the paths that are outlines
 * rather than shapes. Losing them fills the detail lines and the piece becomes a blob.
 */
function stripColour(svg) {
  return (
    svg
      // fill:#abc and stroke:#abc inside a style attribute, with or without a trailing semicolon.
      .replace(/(fill|stroke):\s*#[0-9A-Fa-f]{3,8}\s*;?/g, '')
      // The same as presentation attributes, but never `fill="none"`.
      .replace(/\s(fill|stroke)="#[0-9A-Fa-f]{3,8}"/g, '')
      // An empty style attribute left behind by the above.
      .replace(/\sstyle="\s*"/g, '')
      .replace(/style="\s*;+\s*/g, 'style="')
  );
}

/** Keep only what is inside `<svg>`, plus the viewBox, so the app owns the wrapper element. */
function extract(svg) {
  const open = svg.match(/<svg[^>]*>/);
  if (!open) throw new Error('no <svg> element');
  const viewBox = open[0].match(/viewBox="([^"]*)"/);
  if (!viewBox) throw new Error('no viewBox');
  const inner = svg.slice(svg.indexOf(open[0]) + open[0].length, svg.lastIndexOf('</svg>'));
  return { viewBox: viewBox[1], inner: inner.trim() };
}

const entries = [];
for (const colour of ['w', 'b']) {
  for (const piece of PIECES) {
    const name = `${colour}${piece}`;
    const response = await fetch(`${BASE}/${name}.svg`);
    if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
    const { viewBox, inner } = extract(stripColour(clean(await response.text())));
    entries.push({ key: `${colour}${piece.toLowerCase()}`, viewBox, inner });
    process.stdout.write(`${name} `);
  }
}
process.stdout.write('\n');

const viewBoxes = new Set(entries.map((e) => e.viewBox));
if (viewBoxes.size !== 1) throw new Error(`pieces disagree on viewBox: ${[...viewBoxes].join(', ')}`);

const file = `/**
 * The piece set — **chessnut** by Alexis Luengas, **Apache-2.0**.
 *
 * Generated by \`scripts/vendor-pieces.mjs\`; do not edit by hand.
 *
 * Every colour has been stripped, so these are shapes rather than images: the wrapper element sets
 * \`fill\` and \`stroke\`, the pieces inherit them, and a theme colours all twelve at once. That is
 * what lets both piece colours be measured for contrast against every board colour instead of
 * hoped about. \`fill="none"\` is kept where it appears — it marks the detail lines, and filling
 * those turns a piece into a blob.
 *
 * See \`NOTICES.md\`. cburnett — the set everyone reaches for — is GPLv2+ and cannot be here.
 */

/** Every piece shares one viewBox, checked at generation time. */
export const PIECE_VIEWBOX = '${[...viewBoxes][0]}';

/** Keyed \`wp\`, \`wn\`, … \`bk\` — colour then \`chess.js\`'s own piece letter. */
export const PIECES: Record<string, string> = {
${entries.map((e) => `  ${e.key}: ${JSON.stringify(e.inner)},`).join('\n')}
};
`;

writeFileSync(new URL('../apps/web/src/pieces.ts', import.meta.url), file);
console.log(`wrote apps/web/src/pieces.ts — ${(file.length / 1024).toFixed(1)} kB, viewBox ${[...viewBoxes][0]}`);
