/**
 * Deutsch.
 *
 * Written against `en.ts`, which owns the key set — `i18n.test.ts` fails if a key here is missing or
 * invented. Chess vocabulary is the standard German set (*Schachmatt*, *Patt*, *Remis*, *Weiß*,
 * *Schwarz*, *Läufer*, *Springer*, *Turm*, *Dame*), and the register matches the English: plain,
 * about the game rather than the software, and never blaming the person reading it.
 *
 * Addressed as **du** throughout. This is a chess app somebody plays on their phone, not a bank.
 */

import type { en } from './en.ts';

export const de: Record<keyof typeof en, string> = {
  'nav.sections': 'Bereiche',
  'nav.play': 'Spielen',
  'nav.train': 'Üben',
  'nav.you': 'Du',
  'nav.noRecord':
    'Deine Bilanz erscheint hier, sobald eine Partie signiert ist. Spiele eine zu Ende und signiere das Ergebnis — ein Tippen genügt.',

  'moves.label': 'Züge',
  'moves.empty': 'Die Züge erscheinen hier, während du spielst.',
  'moves.viewingEarlier': 'Du siehst eine frühere Stellung',
  'moves.toStart': 'Zum Anfang',
  'moves.back': 'Ein Zug zurück',
  'moves.forward': 'Ein Zug vor',
  'moves.toLive': 'Zurück zur aktuellen Stellung',
  'moves.namedAfter': '{eco} · benannt nach {plies} Zügen',
  'moves.namedAfterOne': '{eco} · benannt nach {plies} Zug',

  'board.label': 'Schachbrett',
  'board.square': '{square}, {piece}',
  'board.empty': 'leer',
  'board.promote': 'Wähle eine Figur für die Umwandlung',

  'piece.pawn': 'Bauer',
  'piece.knight': 'Springer',
  'piece.bishop': 'Läufer',
  'piece.rook': 'Turm',
  'piece.queen': 'Dame',
  'piece.king': 'König',
  'piece.piece': 'Figur',

  'lobby.title': 'Gegen Freunde spielen',
  'lobby.note':
    'Du bekommst einen Link. Wer ihn öffnet, übernimmt die andere Seite — ganz ohne Konto und ohne Wallet.',
  'lobby.time': 'Bedenkzeit',
  'lobby.youPlay': 'Du spielst',
  'lobby.make': 'Link erstellen',
  'lobby.making': 'Wird erstellt…',
  'lobby.study': 'Oder eine Partie aus einem PGN studieren',
  'lobby.needsWallet':
    'Eine Partie gegen einen Menschen braucht ein Wallet, um das Ergebnis zu signieren. Öffne das hier in Nimiq Pay, oder spiele gegen den Bot — dafür brauchst du gar nichts.',

  'time.bullet': 'Bullet',
  'time.bulletDetail': '1 Minute pro Seite',
  'time.blitz': 'Blitz',
  'time.blitzDetail': '3 Minuten, 2 Sekunden pro Zug',
  'time.rapid': 'Schnellschach',
  'time.rapidDetail': '10 Minuten, 5 Sekunden pro Zug',
  'time.unlimited': 'Ohne Uhr',
  'time.unlimitedDetail': 'Lass dir so viel Zeit, wie du willst',

  'colour.random': 'Zufällig',
  'colour.randomDetail': 'Wie üblich',
  'colour.white': 'Weiß',
  'colour.whiteDetail': 'Du ziehst zuerst',
  'colour.black': 'Schwarz',
  'colour.blackDetail': 'Der andere zieht zuerst',

  'today.title': 'Heute',
  'today.daily': 'Die Aufgabe des Tages lösen',
  'today.game': 'Eine Partie spielen',
  'today.win': 'Eine gewinnen',
  'today.done': 'erledigt',
  'today.notYet': 'noch nicht',

  'puzzles.title': 'Aufgaben',
  'puzzles.rating': 'Aufgaben-Wertung',
  'puzzles.dayInARow': 'Tag in Folge',
  'puzzles.daysInARow': 'Tage in Folge',
  'puzzles.bestStreak': 'beste Serie',
  'puzzles.bestStorm': 'bester Sturm',
  'puzzles.note':
    'Diese Zahlen liegen auf diesem Gerät und niemand signiert sie. Deine Wertung auf der Bilanzseite ist das Gegenteil: zwei Signaturen, und niemand kann sie dir nehmen.',
  'puzzles.daily': 'Aufgabe des Tages',
  'puzzles.dailyDone': 'Die heutige Aufgabe — gelöst',
  'puzzles.dailyDetail': 'Dieselbe Aufgabe, die heute alle anderen bekommen haben.',
  'puzzles.train': 'Üben',
  'puzzles.trainDetail': 'Endlos, und findet dein Niveau von selbst.',
  'puzzles.storm': 'Sturm',
  'puzzles.stormDetail': 'Drei Minuten. So viele du schaffst.',
  'puzzles.streak': 'Serie',
  'puzzles.streakDetail': 'Ohne Uhr. Sie endet beim ersten Fehler.',
  'puzzles.oneIdea': 'Oder eine einzelne Idee üben',
  'coords.title': 'Koordinaten',
  'coords.note':
    'Zu wissen, wo ein Feld liegt, ohne zu zählen, ist die Fähigkeit, die jedes Schachbuch voraussetzt. Dreißig Sekunden, so viele du schaffst.',
  'coords.menuDetail': 'Dreißig Sekunden, um so viele Felder wie möglich zu finden.',
  'coords.mode': 'Modus',
  'coords.findSquare': 'Feld finden',
  'coords.nameSquare': 'Feld benennen',
  'coords.playAs': 'Du spielst',
  'coords.showPieces': 'Figuren zeigen',
  'coords.start': 'Los',
  'coords.again': 'Noch einmal',
  'coords.change': 'Einstellungen ändern',
  'coords.findThis': '{square}',
  'coords.nameThis': 'Benenne das hervorgehobene Feld',
  'coords.thisSquare': 'das zu benennende Feld',
  'coords.score': '{correct} richtig · noch {left} Sekunden',
  'coords.youScored': 'Du hast {score} geschafft.',
  'coords.average': 'Als {side}: {average} im Schnitt, Bestwert {best}',
  'coords.noAverage': 'Als {side}: noch nichts',

  'puzzles.credit': 'Aufgaben aus der offenen Datenbank von Lichess, freigegeben als Gemeingut.',

  'theme.mateIn1': 'Matt in 1',
  'theme.mateIn2': 'Matt in 2',
  'theme.backRankMate': 'Grundreihe',
  'theme.fork': 'Gabeln',
  'theme.pin': 'Fesselungen',
  'theme.skewer': 'Spieße',
  'theme.discoveredAttack': 'Abzugsangriffe',
  'theme.deflection': 'Ablenkung',
  'theme.sacrifice': 'Opfer',
  'theme.hangingPiece': 'Hängende Figuren',
  'theme.endgame': 'Endspiele',
  'theme.promotion': 'Umwandlung',

  'puzzles.stormScore': '{solved} gelöst · noch {left} · Bestwert {best}',
  'puzzles.streakScore': '{solved} in Folge · Bestwert {best}',
  'puzzles.trainScore': 'Deine Aufgaben-Wertung ist {rating} · nur auf diesem Gerät',
  'puzzles.oneDayRun': '{days} Tag in Folge',
  'puzzles.dayRun': '{days} Tage in Folge',
  'puzzles.startARun': 'Löse sie, um eine Serie von Tagen zu starten',
  'puzzles.noPuzzle': 'Es konnte keine Aufgabe geladen werden. Das ist unser Fehler, nicht deiner.',
  'puzzles.themesAndRating': '{themes} · Wertung {rating}',
  'puzzles.ratingOnly': 'Wertung {rating}',
  'puzzles.watchTheirMove': 'Schau dir den Gegenzug an…',
  'puzzles.whiteToPlay': 'Weiß am Zug. Finde den besten Zug.',
  'puzzles.blackToPlay': 'Schwarz am Zug. Finde den besten Zug.',
  'puzzles.rightKeepGoing': 'Richtig. Weiter so.',
  'puzzles.solved': 'Gelöst.',
  'puzzles.solvedToday': 'Gelöst. Damit ist der heutige Tag erledigt.',
  'puzzles.trainOnMore': 'Weitere Aufgaben üben',
  'puzzles.runEnds': 'Der nicht. Die Serie endet bei {solved}.',
  'puzzles.anotherRun': 'Neue Serie starten',
  'puzzles.stormPenalty': 'Der nicht — {seconds} Sekunden.',
  'puzzles.tryAgain': 'Der nicht. Versuch es noch einmal, oder sieh dir die Lösung an.',
  'puzzles.skip': 'Diese überspringen',
  'puzzles.showAnswer': 'Lösung zeigen',
  'puzzles.theMoveWas': 'Der Zug war {move}.',
  'puzzles.thatIsTheLine': 'Das ist die Variante.',
  'puzzles.timeUp': 'Zeit vorbei. {solved} gelöst.',
  'puzzles.runItAgain': 'Noch einmal',

  'pool.allClaimed':
    'Heute wurden bereits alle Belohnungen abgeholt. Der Topf wird aus Staking-Erträgen gespeist und füllt sich morgen wieder auf, statt leerzulaufen.',
  'pool.notFunded': 'Der Aufgaben-Topf ist noch nicht gefüllt. Das Lösen zählt trotzdem für deine Serie.',
  'pool.thereIs': 'Im Topf liegen {amount} für die heutige Aufgabe.',
  'pool.claim': '{amount} abholen',
  'pool.claiming': 'Wird abgeholt…',
  'pool.needsWallet':
    'Die Belohnung wird in NIM ausgezahlt und braucht ein Wallet, in dem sie ankommen kann. Öffne das hier in Nimiq Pay, dann genügt ein Tippen.',
  'pool.deviceReason': 'Damit der Topf eine Abholung von der anderen unterscheiden kann',
  'pool.sent': '{amount} wurden an dein Wallet geschickt. In der Transaktion steht, für welche Aufgabe.',
  'pool.recorded':
    '{amount} gehören dir und die Abholung ist erfasst, aber die Transaktion ist noch nicht raus. Sie wird geschickt — es geht nichts verloren.',

  'common.backToBoard': 'Zurück zum Brett',

  'settings.title': 'Einstellungen',
  'settings.done': 'Fertig',
  'settings.opponent': 'Gegner',
  'settings.opponentHelp': 'Eine Änderung startet eine neue Partie.',
  'settings.board': 'Das Brett',
  'settings.boardColours': 'Brettfarben',
  'settings.wood': 'Holz',
  'settings.slate': 'Schiefer',
  'settings.sea': 'Meer',
  'settings.moveDots': 'Zugpunkte',
  'settings.moveDotsHelp': 'Zeigt, wohin eine angehobene Figur ziehen kann.',
  'settings.coordinates': 'Koordinaten',
  'settings.coordinatesHelp': 'Linienbuchstaben und Reihenzahlen am Rand.',
  'settings.autoQueen': 'Immer in eine Dame umwandeln',
  'settings.autoQueenHelp': 'Schalte das aus, um Turm, Läufer oder Springer zu wählen.',
  'settings.zen': 'Zen',
  'settings.zenHelp': 'Nur das Brett. Sonst nichts auf dem Bildschirm.',
  'settings.blindfold': 'Blind',
  'settings.blindfoldHelp':
    'Versteckt die Figuren; gespielt wird über die Zugliste. Es ist so schwer, wie es klingt.',
  'settings.feedback': 'Rückmeldung',
  'settings.sound': 'Ton',
  'settings.soundHelp': 'Zug, Schlagzug, Schach und Partieende.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHelp': 'Ein kurzes Summen auf Handys, die das können.',
  'settings.language': 'Sprache',
  'settings.languageHelp': 'Folgt Nimiq Pay, solange du keine wählst.',
  'settings.languageAuto': 'Automatisch',

  'level.looksGood': 'Spielt das Erste, was gut aussieht',
  'level.oneAhead': 'Denkt ein bis zwei Züge voraus',
  'level.simpleTactics': 'Sieht die meisten einfachen Taktiken',
  'level.punishes': 'Bestraft eine ungedeckte Figur',

  'result.checkmate': 'Schachmatt',
  'result.stalemate': 'Patt — remis',
  'result.insufficient': 'Nicht genug Material zum Mattsetzen — remis',
  'result.fiftyMove': 'Fünfzig Züge ohne Schlagzug oder Bauernzug — remis',
  'result.repetition': 'Dieselbe Stellung fünfmal — remis',
  'result.gameOver': 'Partie beendet',
  'result.whiteWins': ' — Weiß gewinnt',
  'result.blackWins': ' — Schwarz gewinnt',
  'result.check': ' — Schach',

  'record.puzzleRating': 'Taktikwertung',
  'puzzles.signing': 'Diese Runde wird signiert…',
  'puzzles.seeRecord': 'Deine Bilanz ansehen',
  'puzzles.makeCount': 'Meine Runden sollen zählen',
  'puzzles.loading': 'Aufgaben werden geladen…',
  'puzzles.dailyDoneNote': 'Die heutige Aufgabe ist schon gelöst. Komm morgen wieder.',
  'puzzles.trainMore': 'Mehr Aufgaben üben',
  'puzzles.backToBoard': 'Zurück zum Brett',
  'game.claim': 'Eine Schachwertung, die dir niemand nehmen kann. Beide Spieler signieren das Ergebnis — nicht wir.',
  'game.resign': 'Aufgeben',
  'game.resignAgain': 'Zum Aufgeben noch einmal tippen',
  'game.takeback': 'Zurücknehmen',
  'game.backToStart': 'Zurück am Anfang. Du bist am Zug.',
  'game.takenBack': 'Zurückgenommen. Du bist am Zug.',
  'game.flip': 'Brett drehen',
  'game.newGame': 'Neue Partie',
  'game.playFriend': 'Gegen Freunde spielen',
  'game.leaveZen': 'Zen verlassen oder Einstellungen ändern',
  'game.resignedBlackWins': 'Du hast aufgegeben — Schwarz gewinnt',
  'game.resignedWhiteWins': 'Du hast aufgegeben — Weiß gewinnt',
  'game.rematch': 'Revanche',
  'game.review': 'Sieh, wo es schiefging',
  'game.youVs': 'Du gegen {bot} · {moves} Züge',
  'game.seeRecord': 'Deine Bilanz ansehen',
  'game.yourMoveAsWhite': 'Du bist am Zug. Du hast Weiß, gegen {bot}.',
  'game.botIsWhite': '{bot} hat Weiß und ist am Zug.',
  'game.youFlagged': 'Deine Zeit ist abgelaufen.',
  'game.theyFlagged': 'Seine Zeit ist abgelaufen — du gewinnst.',
  'game.clock': 'Uhr',
  'game.clockHelp': 'Eine Änderung startet eine neue Partie.',
  'game.newGameAgainst': 'Neue Partie gegen {bot}.',

  'sign.button': 'Signiere das Ergebnis, damit es zählt',
  'sign.waiting': 'Warte auf dein Wallet…',
  'sign.whatWasSigned': 'Was signiert wurde',
  'sign.done': 'Signiert. Dieses Ergebnis gehört dir, und jeder kann es ohne uns prüfen.',
  'sign.demoDone':
    'Mit dem Ersatz-Wallet signiert. Die Signatur ist echt und wird verifiziert — aber ihr Schlüssel steht in unserem Quellcode, also beweist sie den Mechanismus, nicht dich.',
  'sign.needsNimiqPay':
    'Signiert wird in der Nimiq-Pay-App. Öffne das hier dort, dann gehört das Ergebnis dir.',
  'sign.invitation':
    'Signiere das Ergebnis, dann gehört es dir — ein Eintrag, den niemand widerrufen kann und den man ohne uns prüfen kann.',

  'live.checkmate': 'Schachmatt',
  'live.resignation': 'Aufgabe',
  'live.timeout': 'Zeit',
  'live.stalemate': 'Patt',
  'live.insufficient': 'Nicht genug Material zum Mattsetzen',
  'live.repetition': 'Dreifache Stellungswiederholung',
  'live.fiftyMove': 'Fünfzig-Züge-Regel',
  'live.agreement': 'Remis vereinbart',
  'live.reasonDraw': '{reason} — remis',
  'live.reasonYouWin': '{reason} — du gewinnst',
  'live.reasonYouLose': '{reason} — du verlierst',
  'live.reasonYouWinStop': '{reason} — du gewinnst.',
  'live.reasonYouLoseStop': '{reason} — du verlierst.',
  'live.waitingForSomebody': 'Warte darauf, dass jemand deinen Link öffnet.',
  'live.watching': 'Du siehst dieser Partie zu.',
  'live.yourMove': 'Du bist am Zug.',
  'live.theirMove': 'Der andere ist am Zug.',
  'live.sendThisLink': 'Schick diesen Link an den, gegen den du spielen willst',
  'live.linkLabel': 'Der Link zu dieser Partie',
  'live.copy': 'Kopieren',
  'live.copied': 'Kopiert',
  'live.pressToCopy': 'Zum Kopieren drücken',
  'live.claimWin': 'Sieg auf Zeit beanspruchen',
  'live.offerDraw': 'Remis anbieten',
  'live.sign': 'Ergebnis signieren',
  'live.signed': 'Signiert',
  'live.bothSignatures':
    'Beide Signaturen machen daraus eine Wertung, die dir niemand nehmen kann. Du kannst jetzt signieren; der andere signiert, wann immer er den Link öffnet.',
  'live.gameTitle': '{white} gegen {black} · {moves} Züge',
  'live.theyWantAnother': 'Der andere will noch eine Partie — mitspielen',
  'live.waitingForRematch': 'Warte darauf, dass er deiner Revanche beitritt.',
  'live.playAgain': 'Noch einmal spielen',
  'live.settingUp': 'Wird vorbereitet…',
  'live.noHeightYet':
    'Die Blockhöhe für diese Partie ist noch nicht da, und ein Ergebnis braucht eine, um gegenüber deinen anderen Partien einsortiert zu werden. Warte kurz und signiere noch einmal — es geht nichts verloren.',
  'live.publicLink': 'Einen Link holen, den jeder prüfen kann',
  'live.trouble': 'Probleme, die Partie zu erreichen. Wir versuchen es weiter — es geht nichts verloren.',
  'live.opening': 'Partie wird geöffnet…',
  'live.watchOnly':
    'Du kannst dieser Partie zusehen. Zum Mitspielen öffne sie in Nimiq Pay, damit sie eine Adresse zum Signieren hat.',
  'live.alreadyTwo': 'Diese Partie hat schon zwei Spieler. Du siehst zu.',
  'live.expired': 'Diese Partie ist beendet oder abgelaufen. Links gelten einen Tag.',
  'live.leaveWarning':
    'Diese Partie verlassen? Deine Uhr läuft weiter, und dein Gegner kann den Sieg beanspruchen, wenn sie abläuft.',
  'live.stay': 'Bleiben',
  'live.leaveAnyway': 'Trotzdem verlassen',

  'fail.offline':
    'Die Partie war nicht erreichbar. Prüf deine Verbindung — es geht nichts verloren, und es geht dort weiter, wo du aufgehört hast.',
  'fail.noGame': 'Diese Partie ist beendet oder abgelaufen. Links gelten einen Tag.',
  'fail.gameFull': 'Hier spielen bereits zwei Leute. Du kannst zusehen.',
  'fail.notYourTurn': 'Der andere ist am Zug. Dein Brett holt gleich auf.',
  'fail.notAPlayer': 'Du siehst dieser Partie zu, statt sie zu spielen.',
  'fail.notStarted': 'Bisher hat niemand deinen Link geöffnet, also gibt es niemanden, gegen den du ziehen könntest.',
  'fail.gameOver': 'Diese Partie ist bereits beendet.',
  'fail.illegalMove': 'Dieser Zug ist in dieser Stellung nicht erlaubt. Das Brett steht wieder wie vorher.',
  'fail.stale':
    'Die Partie ist weitergelaufen, während das unterwegs war. Dein Brett ist jetzt aktuell — versuch es noch einmal.',
  'fail.notFlagged': 'Seine Uhr ist noch nicht abgelaufen.',
  'fail.ownFlag': 'Abgelaufen ist deine eigene Uhr, nicht seine.',
  'fail.notOver': 'Eine Partie lässt sich erst signieren, wenn sie beendet ist.',
  'fail.serverError':
    'Bei uns ist etwas schiefgegangen. Deine Partie ist sicher — sie liegt auf dem Server, und die nächste Abfrage findet sie.',
  'fail.tooMany':
    'Das waren viele Anfragen auf einmal. Warte ein paar Sekunden — deine Partie ist sicher, und es ist nichts verloren.',
  'fail.tooLarge': 'Diese Anfrage war zu groß zum Senden. Das ist unser Fehler, nicht deiner.',
  'fail.declined': 'Du hast nicht signiert. Es wurde nichts erfasst, und du kannst jederzeit signieren.',
  'fail.cancelled': 'Abgebrochen. Es ist nichts verloren.',
  'fail.badSignature':
    'Dein Wallet hat eine Signatur zurückgegeben, die diese App nicht lesen konnte. Bitte melde das — es ist unser Fehler, nicht deiner.',
  'fail.noStorage':
    'Dieser Browser lässt die App nichts speichern. Es funktioniert vorerst alles, aber es ist weg, sobald du den Tab schließt.',
  'fail.refused': 'Dieser Browser hat das abgelehnt. Es ist nichts verloren.',
  'fail.chunk': 'Ein Teil der App konnte nicht geladen werden. Lade die Seite neu, dann ist er wieder da.',
  'fail.network': 'Dein Gerät hat das Netz nicht erreicht. Es ist nichts verloren — versuch es gleich noch einmal.',
  'fail.notConfirmed': 'Du hast das nicht bestätigt. Es ist nichts passiert.',
  'fail.syncing': 'Nimiq Pay holt noch zur Blockchain auf. Gib ihm ein paar Sekunden.',
  'fail.somethingWith': 'Etwas ist schiefgegangen: {detail}',
  'fail.something': 'Etwas ist schiefgegangen. Es wurde nichts signiert und nichts ist verloren.',
  'fail.noWalletSign': 'Signiert wird in der Nimiq-Pay-App. Öffne das hier dort.',
  'fail.noAddress': 'Das Wallet hat keine Adresse zurückgegeben.',
  'fail.phoneNetwork': 'Dein Handy hat das Netz nicht erreicht. Es ist nichts verloren — versuch es gleich noch einmal.',
  'fail.somethingSigning': 'Etwas ist schiefgegangen. Es wurde nichts signiert.',
  'fail.timeout': '{step} — Nimiq Pay hat nicht geantwortet. Öffne das Wallet und versuch es noch einmal.',

  'wallet.sharingAddress': 'Deine Adresse wird geteilt',
  'wallet.signing': 'Wird signiert',
  'wallet.checkingSync': 'Prüfen, ob das Wallet aufgeholt hat',
  'wallet.readingHeight': 'Blockhöhe wird gelesen',
  'wallet.identifyingDevice': 'Dieses Gerät wird erkannt',

  'record.allPublished':
    'Jede Partie hier wurde mit einem Schlüssel signiert, der in unserem Quellcode steht — dem Ersatz-Wallet oder dem Bot. Die Signaturen sind gültig, und jeder kann weitere davon erzeugen; das zeigt also, wie die Zahl zustande kommt, nicht wessen sie ist.',
  'record.somePublished':
    '{published} dieser {total} Partien wurden mit einem Schlüssel signiert, der in unserem Quellcode steht — dem Ersatz-Wallet oder dem Bot. Diese Signaturen sind gültig, und jeder kann weitere davon erzeugen.',
  'record.title': 'Bilanz',
  'record.noRatedGames': 'Noch keine gewerteten Partien',
  'record.oneRatedGame': '{games} gewertete Partie',
  'record.ratedGames': '{games} gewertete Partien',
  'record.oneOpponent': '{count} verschiedener Gegner',
  'record.opponents': '{count} verschiedene Gegner',
  'record.provisional': 'Vorläufig, bis {needed} verschiedene Gegner signiert haben. Bisher {so_far}.',
  'record.recompute': 'Hier neu berechnen',
  'record.recomputeNote':
    'Leitet jede Wertung unten in diesem Browser neu her, allein aus den Signaturen. Unser Server wird dabei nichts gefragt.',
  'record.checking': 'Jede Signatur wird geprüft…',
  'record.checkedOne': '{checked} signierte Partie hier geprüft, in diesem Browser.',
  'record.checkedMany': '{checked} signierte Partien hier geprüft, in diesem Browser.',
  'record.noneRate': 'Keine davon zählt, also bleibt die Wertung auf ihrem Startwert.',
  'record.someRate': '{games} davon zählen.',
  'record.agrees': 'Dieser Browser kommt auf {reached} — dieselbe Zahl wie diese Seite.',
  'record.disagrees':
    'Dieser Browser kommt auf {reached} und diese Seite sagt {shown}. Wenn das auseinandergeht, hat diese Seite unrecht.',
  'record.leftOutUnsigned': '{count} noch nicht von beiden Spielern signiert',
  'record.leftOutInvalid': '{count} nicht verifiziert',
  'record.leftOut': 'Nicht berücksichtigt: {detail}.',
  'record.empty': 'Auf diesem Wallet gibt es noch keine signierten Partien.',
  'record.emptyNote':
    'Das ist weder ein schlechtes noch ein gutes Zeichen — es ist ein Wallet ohne Bilanz. Spiel eine Partie und signiere das Ergebnis.',
  'record.everyGame': 'Alle Partien, in der Reihenfolge, in der sie zählen',
  'record.won': 'Gewonnen',
  'record.lost': 'Verloren',
  'record.drew': 'Remis',
  'record.casual': 'Freundschaftlich — zählt nie',
  'record.tooShort': 'Unter {moves} Zügen — erfasst, aber nicht gewertet',
  'record.farmed': 'Zu viele Partien gegen diesen Gegner — es bewegt keine der beiden Wertungen mehr',
  'record.gameLine': '{termination} · {moves} Züge · Block {block}',
  'record.footer':
    'Jede Zahl hier ist aus Signaturen abgeleitet, die beide Spieler gemacht haben. Niemand kann sie ändern — weder die Person, um die es geht, noch wir.',

  'judge.best': 'Bester Zug',
  'judge.bests': 'beste Züge',
  'judge.good': 'Gut',
  'judge.goods': 'gute Züge',
  'judge.inaccuracy': 'Ungenauigkeit',
  'judge.inaccuracies': 'Ungenauigkeiten',
  'judge.mistake': 'Fehler',
  'judge.mistakes': 'Fehler',
  'judge.blunder': 'Grober Fehler',
  'judge.blunders': 'grobe Fehler',

  'study.title': 'Eine Partie studieren',
  'study.note':
    'Füge eine Partie als PGN ein — von Lichess, Chess.com, aus einem Turnier, von überall — oder studiere die, die du gerade gespielt hast. Hier wird nichts signiert und nichts berührt deine Wertung.',
  'study.handedNote':
    'Die Partie, die du gerade gespielt hast. Hier wird nichts signiert und nichts berührt deine Wertung — das hier ist zum Anschauen.',
  'study.pasteLabel': 'Eine Partie als PGN einfügen',
  'study.open': 'Öffnen',
  'study.analyse': 'Diese Partie analysieren',
  'study.looking': 'Die Partie wird durchgesehen…',
  'study.lookingProgress': 'Die Partie wird durchgesehen… {done} von {total} Zügen.',
  'study.wasBest': '{number} {san} — der beste Zug hier.',
  'study.wasGood': '{number} {san} — ein guter Zug.',
  'study.wasWorse': '{number} {san} — {label}. {better} war besser, um {lost} Punkte Gewinnchance.',
  'study.acpl': '{acpl} Centibauern Verlust pro Zug',
  'study.whiteAhead': 'Weiß steht besser — {percent} Prozent',
  'study.blackAhead': 'Schwarz steht besser — {percent} Prozent',
  'study.nothingToComplain': 'nichts zu beanstanden',
  'study.caveat':
    'Durchgesehen von der eigenen Engine dieser App, auf deinem Gerät — etwa Vereinsstärke, nicht Stockfish. Sie findet die groben Fehler einer gewöhnlichen Partie und widerspricht keinem Großmeister.',
  'study.reviewed': 'Die Partie ist durchgesehen. Geh sie durch, um jeden Zug bewertet zu sehen.',
  'study.analysisFailed': 'Die Analyse wurde abgebrochen: {detail}. Das ist unser Fehler — bitte melde ihn.',
  'study.playersVs': '{white} gegen {black}',
  'study.animported': 'Eine importierte Partie',
  'study.heading': '{players} · {moves} Züge',
  'study.loaded': '{plies} Züge geladen. Geh sie mit den Pfeiltasten durch.',

  'cert.title': 'Eine signierte Partie',
  'cert.fetching': 'Partie wird geholt…',
  'cert.stillPlaying': 'Diese Partie läuft noch. Das Zertifikat erscheint, wenn sie endet.',
  'cert.unreconstructable': 'Diese Partie lässt sich nicht rekonstruieren, also ist hier nichts prüfbar.',
  'cert.onlyOne': 'Bisher hat nur ein Spieler signiert. Zum Eintrag wird es, wenn beide signiert haben.',
  'cert.verified': 'Beide Spieler haben dieses Ergebnis signiert, und dieser Browser hat gerade beide Signaturen geprüft.',
  'cert.bad': 'Diese Signaturen gehen nicht auf. Glaub diesem Ergebnis nicht.',
  'cert.nothingAsked':
    'Für diesen Schluss wurde unser Server um nichts gebeten außer um die Partie selbst — die Signaturen wurden hier auf deinem Gerät gegen genau den Text geprüft, den beide Spieler signiert haben.',
  'cert.checkFailed': 'Die Prüfung ist fehlgeschlagen: {reason}.',
  'cert.unknown': 'unbekannt',
  'cert.winnersRecord': 'Bilanz des Siegers ansehen',
  'cert.playYourself': 'Spiel selbst eine Partie',
  'cert.signed': 'signiert',
  'cert.notSignedYet': 'noch nicht signiert',

  'certificate.abandoned': 'Abgebrochen',
  'certificate.cannotDraw': 'Dieser Browser kann kein Zertifikat zeichnen.',
  'certificate.noPicture': 'Das Bild konnte nicht erstellt werden.',
  'certificate.whiteWins': 'Weiß gewinnt',
  'certificate.blackWins': 'Schwarz gewinnt',
  'certificate.drawn': 'Remis',
  'certificate.rated': 'gewertet',
  'certificate.casual': 'freundschaftlich',
  'certificate.summary': '{reason} · {moves} Züge · {kind}',
  'certificate.bothSigned': 'Beide Spieler haben dieses Ergebnis signiert',
  'certificate.evidence': 'Nimiq-Block {block} · Partie {game}… · jeder kann das auf {where} prüfen',
  'certificate.signatureOf': 'Signatur von {side}',
  'certificate.tagline': 'Eine Wertung, die niemand vergeben hat und niemand widerrufen kann.',

  'share.asPicture': 'Als Bild teilen',
  'share.asPgn': 'Als PGN speichern',
  'share.sent': 'Gesendet.',
  'share.savedPicture': 'Als Bild gespeichert.',
  'share.savedPgn': 'Als PGN gespeichert, das jedes Schachprogramm liest.',
  'share.notOnDevice': 'Diese Partie ist nicht mehr auf diesem Gerät.',
  'share.didNotWork': 'Das hat auf diesem Gerät nicht geklappt. Die Partie ist so oder so sicher.',

  'sign.notOver': 'Diese Partie ist noch nicht zu Ende.',
  'sign.syncing':
    'Nimiq Pay holt noch zur Blockchain auf. Gib ihm ein paar Sekunden und signiere noch einmal.',
  'sign.noHeight':
    'Nimiq Pay konnte die Blockhöhe gerade nicht lesen, und eine Partie braucht eine, um einsortiert zu werden. Versuch es gleich noch einmal.',
  'sign.notYourGame': 'Dieses Wallet hat diese Partie nicht gespielt, also gibt es hier nichts zu signieren.',

  'api.offline': 'Die Partie war nicht erreichbar. Prüf deine Verbindung.',
  'api.something': 'Etwas ist schiefgegangen.',
  'api.badShape':
    'Der Server hat etwas geschickt, das diese App nicht lesen konnte. Das ist unser Fehler, nicht deiner — deine Partie liegt sicher auf dem Server.',
  'poolApi.offline': 'Der Topf war nicht erreichbar.',
  'poolApi.refused': 'Diese Abholung war nicht möglich.',
  'poolApi.alreadyClaimed': 'Du hast heute schon abgeholt. Um Mitternacht wechselt die Aufgabe, und das hier auch.',
  'poolApi.deviceClaimed':
    'Dieses Gerät hat heute schon abgeholt — eine pro Gerät, und genau das verhindert, dass ein Skript den Topf leert.',
  'poolApi.notFunded':
    'Der Topf ist im Moment nicht gefüllt, es gibt also nichts abzuholen. Das Lösen zählt trotzdem für deine Serie.',
  'poolApi.needsNimiqPay':
    'Zum Abholen braucht es Nimiq Pay, denn das sagt dem Topf, dass zwei Abholungen von zwei verschiedenen Leuten kommen.',
  'poolApi.unreachable':
    'Der Topf war nicht erreichbar. Deine Lösung ist sicher — versuch es gleich noch einmal.',

  'send.needsNimiqPay': 'NIM senden geschieht in der Nimiq-Pay-App. Öffne das hier dort.',
  'send.memoTooLong': 'Diese Nachricht ist zu lang für eine Nimiq-Transaktion. Das ist unser Fehler.',
  'send.badAmount': 'Das ist kein Betrag, der sich senden lässt.',
  'send.waiting': 'Warte auf dein Wallet',
  'send.declined': 'Es wurde nichts gesendet. Deine NIM sind, wo sie waren.',
  'send.failed': 'Das konnte nicht gesendet werden. Aus deinem Wallet ist nichts abgegangen.',
  'send.tip': 'Schick ihm {amount} NIM',
  'send.tipTitle': 'Gute Partie?',
  'send.tipNote':
    'Schick NIM direkt aus deinem Wallet. Sie gehen nicht über uns, und in der Transaktion steht, für welche Partie.',
  'send.tipSent': 'Gesendet. {amount} NIM sind von deinem Wallet in seines gegangen.',
  'send.poolTitle': 'Gib etwas zurück',
  'send.poolNote':
    'Der Topf zahlt einem Fremden etwas dafür, dass er die Tagesaufgabe löst. Jeder kann etwas hinzufügen, und jede Auszahlung steht mit der Aufgabe darin auf der Blockchain.',
  'send.poolAdd': '{amount} NIM in den Topf geben',
  'send.poolSent': 'Gesendet. {amount} NIM liegen im Topf für den Nächsten, der löst.',
  'send.sending': 'Warte auf dein Wallet…',

  'app.broke': 'Etwas ist kaputtgegangen',

  /* ---------------------------------------------------------------- the portable record */
  'record.take': 'Nimm deine Bilanz mit',
  'record.takeNote':
    'Eine Datei mit jeder signierten Partie und jedem Puzzle-Lauf auf diesem Ger\u00e4t. Jeder kann sie pr\u00fcfen \u2014 ohne diese Seite und ohne uns zu fragen.',
  'record.takeButton': 'Bilanz speichern',
  'record.takeEmpty': 'Auf diesem Ger\u00e4t ist noch nichts signiert.',
  'record.recordSent': 'Gesendet \u2014 {games} Partien und {runs} Puzzle-L\u00e4ufe.',
  'record.recordSaved': 'Gespeichert \u2014 {games} Partien und {runs} Puzzle-L\u00e4ufe.',
  'record.recordSkipped': '{count} ausgelassen: nicht von beiden Seiten signiert oder aus dem anderen Netz.',

  /* ---------------------------------------------------------------- the verify screen */
  'verify.title': 'Eine Bilanz pr\u00fcfen',
  'verify.intro':
    'Jemand hat dir eine Scoresheet-Bilanz geschickt? \u00d6ffne sie hier. Dein Browser pr\u00fcft jede Signatur und errechnet die Wertung selbst. Nichts wird hochgeladen, und diese Seite braucht unseren Server nicht.',
  'verify.choose': 'Datei ausw\u00e4hlen',
  'verify.checking': 'Jede Signatur wird gepr\u00fcft\u2026',
  'verify.unreadable': 'Diese Datei konnte nicht gelesen werden.',
  'verify.notARecord': 'Das ist keine Scoresheet-Bilanz.',
  'verify.oneGame': '1 Partie gepr\u00fcft und {runs} Puzzle-L\u00e4ufe.',
  'verify.manyGames': '{games} Partien gepr\u00fcft und {runs} Puzzle-L\u00e4ufe.',
  'verify.rating': 'Wertung {rating}, aus {games} gewerteten Partien gegen {opponents} verschiedene Personen.',
  'verify.noneRate': 'Keine dieser Partien ist gewertet, es gibt also keine Wertung zu pr\u00fcfen.',
  'verify.provisional': 'Vorl\u00e4ufig: eine Wertung gilt nach zehn verschiedenen Gegnern als gefestigt.',
  'verify.puzzleRating': 'Puzzle-Wertung {rating}.',
  'verify.findings': 'Was nicht aufging',
  'verify.badSignature': 'Partie {id}: die Signatur von {side} passt nicht.',
  'verify.notTheirs': 'Eine Partie, die jemand anderem geh\u00f6rt, wurde ausgelassen.',
  'verify.wrongChain': 'Eine Partie aus dem anderen Netz wurde ausgelassen.',
  'verify.malformed': 'Ein Eintrag war nicht lesbar: {detail}',
  'verify.gameRootMismatch': 'Die Partien ergeben nicht den Fingerabdruck, den diese Bilanz angibt. Danach wurde etwas hinzugef\u00fcgt oder entfernt.',
  'verify.runRootMismatch': 'Die Puzzle-L\u00e4ufe ergeben nicht den Fingerabdruck, den diese Bilanz angibt.',
  'verify.anchorBefore': 'Diese Bilanz will vor einer ihrer eigenen Partien in der Kette verankert worden sein.',
  'verify.anchored': 'In der Nimiq-Kette verankert, nach der letzten enthaltenen Partie.',
  'verify.caveat':
    'Das beweist, dass diese Partien stattfanden und nicht ver\u00e4ndert wurden. Es beweist nicht, dass die Liste vollst\u00e4ndig ist \u2014 wer selbst ver\u00f6ffentlicht, kann eine Niederlage weglassen.',

  'study.tryAgain': 'Selbst versuchen',
  'study.tryGiveUp': 'Zeig es mir',
  'study.tryPrompt': 'Du bist am Zug. Finde etwas Besseres als das, was du gespielt hast.',
  'study.tryThinking': 'Wird gepr\u00fcft\u2026',
  'study.tryFound': '{san} \u2014 genau das. Das wollte die Engine.',
  'study.tryBetter': '{san} ist besser als dein Zug, aber nicht das Beste. Es kostet {lost} Punkte statt dessen.',
  'study.tryNo': '{san} kostet {lost} Punkte \u2014 nicht besser als dein Zug. Versuch einen anderen.',
  'study.tryUnknown': 'Die Engine hat nicht rechtzeitig geantwortet, also bleibt dieser Zug unbewertet.',

  'study.trainThis': 'Das üben',
  'study.trainChecking': 'Wird geprüft, ob daraus ein faires Rätsel wird…',
  'study.trainAdded': 'Zum Training hinzugefügt. Du triffst diese Stellung wieder.',
  'study.trainAlready': 'Diese Stellung ist schon in deinem Training.',
  'study.trainNotUnique': 'Nicht hinzugefügt: hier gibt es mehr als einen guten Zug, das wäre kein faires Rätsel.',
  'study.trainNotSuitable': 'Nicht hinzugefügt: der beste Zug hier ist nichts, wonach ein Rätsel fragen kann.',
  'study.trainNotSound': 'Nicht hinzugefügt: ein längerer Blick war mit dem ersten nicht einverstanden.',
  'study.trainUnknown': 'Die Engine hat nicht rechtzeitig geantwortet, also wurde nichts hinzugefügt.',
  'puzzles.mine': 'Deine eigenen Fehler',
  'puzzles.mineDetail': '{count} warten. Stellungen, die du falsch hattest, die schlimmsten zuerst.',
  'puzzles.mineDone': 'Das waren alle. Du hast jeden gespeicherten Fehler durchgearbeitet.',

  /* ---------------------------------------------------------------- tournaments */
  'lobby.tourneyTitle': 'Ein Turnier ausrichten',
  'lobby.tourneyNote': 'Jeder gegen jeden, ab neun Spielern Schweizer System. Du bekommst einen Link für die Mitspieler.',
  'lobby.seats': 'Spieler',
  'lobby.seats4': 'Vier',
  'lobby.seats4Detail': 'Sechs Partien, je eine Runde',
  'lobby.seats6': 'Sechs',
  'lobby.seats6Detail': 'Fünfzehn Partien',
  'lobby.seats8': 'Acht',
  'lobby.seats8Detail': 'Jeder gegen jeden',
  'lobby.seats12': 'Zwölf',
  'lobby.seats12Detail': 'Schweizer System, fünf Runden',
  'lobby.hold': 'Ein Turnier ausrichten',
  'lobby.tourneyName': 'Turnier',
  'tourney.title': 'Turnier',
  'tourney.loading': 'Turnier wird geladen\u2026',
  'tourney.notFound': 'Zu diesem Link gibt es kein Turnier.',
  'tourney.unavailable': 'Dieses Turnier konnte gerade nicht geladen werden.',
  'tourney.open': 'Offen \u2014 {entrants} von {seats} Pl\u00e4tzen belegt.',
  'tourney.running': 'L\u00e4uft \u2014 {entrants} Spieler.',
  'tourney.finished': 'Beendet \u2014 {entrants} Spieler.',
  'tourney.agrees': 'Dieser Browser hat die Tabelle selbst aus den Partien errechnet und kam auf dieselbe Reihenfolge.',
  'tourney.disagrees': 'Dieser Browser errechnet aus diesen Partien eine andere Tabelle. Etwas stimmt nicht.',
  'tourney.standings': 'Tabelle',
  'tourney.games': 'Partien',
  'tourney.round': 'Runde {round}',
  'tourney.toPlay': 'noch offen',
  'tourney.prize': '{nim} NIM',
  'tourney.caveat': 'Jede Partie oben wurde in diesem Browser gegen ihre beiden Signaturen geprüft. Die Reihenfolge folgt aus diesen Partien, und du hast gerade zugesehen, wie sie entstand.',
  'tourney.agreesSigned': 'Dieser Browser hat alle {games} signierten Partien selbst geprüft und dieselbe Tabelle errechnet — ohne uns zu fragen.',
  'tourney.dropped': '{games} eingereichte Partien ließen sich nicht prüfen und blieben unberücksichtigt.',
  'tourney.caveatUnchecked': 'Die Reihenfolge folgt aus diesen Ergebnissen, und das hast du gerade selbst geprüft. Ob dies die Ergebnisse sind, ist eine andere Frage — die beantwortet jede Partie auf ihrem eigenen Zertifikat.',
  'tourney.join': 'Bei diesem Turnier mitspielen',
  'tourney.joinFailed': 'Das hat nicht geklappt. Vielleicht sind die Plätze schon voll.',
  'tourney.yours': 'Deine Partien',
  'tourney.playThem': 'noch nicht gespielt',
  'tourney.report': 'Partie einreichen',
  'tourney.reportFailed': 'Diese Partie wurde nicht angenommen. Sie muss von euch beiden signiert sein.',
  'tourney.back': 'Zur\u00fcck',
};
