/**
 * Español.
 *
 * Written against `en.ts`, which owns the key set — `i18n.test.ts` fails if a key here is missing or
 * invented. Chess vocabulary is the standard Spanish set (*jaque mate*, *tablas*, *ahogado*,
 * *blancas*, *negras*), and the register matches the English: plain, about the game rather than the
 * software, and never blaming the person reading it.
 */

import type { en } from './en.ts';

export const es: Record<keyof typeof en, string> = {
  'nav.sections': 'Secciones',
  'nav.play': 'Jugar',
  'nav.train': 'Entrenar',
  'nav.you': 'Tú',
  'nav.noRecord':
    'Tu historial aparece aquí en cuanto firmes una partida. Termina una y firma el resultado — es un toque.',

  'moves.label': 'Jugadas',
  'moves.empty': 'Las jugadas aparecen aquí mientras juegas.',
  'moves.viewingEarlier': 'Estás viendo una posición anterior',
  'moves.toStart': 'Ir al principio',
  'moves.back': 'Jugada anterior',
  'moves.forward': 'Jugada siguiente',
  'moves.toLive': 'Volver a la posición actual',
  'moves.namedAfter': '{eco} · nombrada tras {plies} jugadas',
  'moves.namedAfterOne': '{eco} · nombrada tras {plies} jugada',

  'board.label': 'Tablero de ajedrez',
  'board.square': '{square}, {piece}',
  'board.empty': 'vacía',
  'board.promote': 'Elige una pieza para coronar',

  'piece.pawn': 'peón',
  'piece.knight': 'caballo',
  'piece.bishop': 'alfil',
  'piece.rook': 'torre',
  'piece.queen': 'dama',
  'piece.king': 'rey',
  'piece.piece': 'pieza',

  'lobby.title': 'Jugar con un amigo',
  'lobby.note':
    'Recibes un enlace. Quien lo abra toma el otro bando — no necesita cuenta ni cartera para jugar.',
  'lobby.time': 'Tiempo',
  'lobby.youPlay': 'Juegas con',
  'lobby.make': 'Crear el enlace',
  'lobby.making': 'Creándolo…',
  'lobby.study': 'O estudia una partida desde un PGN',
  'lobby.needsWallet':
    'Una partida contra otra persona necesita una cartera para firmar el resultado. Ábrelo en Nimiq Pay, o juega contra el bot — eso no necesita nada.',

  'time.bullet': 'Bullet',
  'time.bulletDetail': '1 minuto por bando',
  'time.blitz': 'Blitz',
  'time.blitzDetail': '3 minutos, 2 segundos por jugada',
  'time.rapid': 'Rápidas',
  'time.rapidDetail': '10 minutos, 5 segundos por jugada',
  'time.unlimited': 'Sin reloj',
  'time.unlimitedDetail': 'Tómate el tiempo que quieras',

  'colour.random': 'Al azar',
  'colour.randomDetail': 'Lo normal',
  'colour.white': 'Blancas',
  'colour.whiteDetail': 'Mueves primero',
  'colour.black': 'Negras',
  'colour.blackDetail': 'Mueven primero',

  'today.title': 'Hoy',
  'today.daily': 'Resuelve el ejercicio del día',
  'today.game': 'Juega una partida',
  'today.win': 'Gana una',
  'today.done': 'hecho',
  'today.notYet': 'todavía no',

  'puzzles.title': 'Ejercicios',
  'puzzles.rating': 'elo de ejercicios',
  'puzzles.dayInARow': 'día seguido',
  'puzzles.daysInARow': 'días seguidos',
  'puzzles.bestStreak': 'mejor racha',
  'puzzles.bestStorm': 'mejor tormenta',
  'puzzles.note':
    'Estos números viven en este dispositivo y nadie los firma. Tu elo en la página de historial es lo contrario: dos firmas, y nadie puede quitártelo.',
  'puzzles.daily': 'Ejercicio del día',
  'puzzles.dailyDone': 'El ejercicio de hoy — hecho',
  'puzzles.dailyDetail': 'El mismo ejercicio que ha recibido todo el mundo hoy.',
  'puzzles.train': 'Entrenar',
  'puzzles.trainDetail': 'Sin fin, y encuentra tu nivel sobre la marcha.',
  'puzzles.storm': 'Tormenta',
  'puzzles.stormDetail': 'Tres minutos. Todos los que puedas.',
  'puzzles.streak': 'Racha',
  'puzzles.streakDetail': 'Sin reloj. Termina en cuanto fallas.',
  'puzzles.oneIdea': 'O entrena una sola idea',
  'coords.title': 'Coordenadas',
  'coords.note':
    'Saber dónde está una casilla sin contar es la habilidad que todo libro de ajedrez da por sabida. Treinta segundos, todas las que puedas.',
  'coords.menuDetail': 'Treinta segundos para encontrar todas las casillas que puedas.',
  'coords.mode': 'Modo',
  'coords.findSquare': 'Encuentra la casilla',
  'coords.nameSquare': 'Nombra la casilla',
  'coords.playAs': 'Juegas con',
  'coords.showPieces': 'Mostrar las piezas',
  'coords.start': 'Empezar',
  'coords.again': 'Otra vez',
  'coords.change': 'Cambiar los ajustes',
  'coords.findThis': '{square}',
  'coords.nameThis': 'Nombra la casilla iluminada',
  'coords.thisSquare': 'la casilla a nombrar',
  'coords.score': '{correct} aciertos · quedan {left} segundos',
  'coords.youScored': 'Has hecho {score}.',
  'coords.average': 'Con {side}: {average} de media, mejor {best}',
  'coords.noAverage': 'Con {side}: todavía nada',

  'puzzles.credit': 'Ejercicios de la base de datos abierta de Lichess, liberada al dominio público.',

  'theme.mateIn1': 'Mate en 1',
  'theme.mateIn2': 'Mate en 2',
  'theme.backRankMate': 'Última fila',
  'theme.fork': 'Horquillas',
  'theme.pin': 'Clavadas',
  'theme.skewer': 'Rayos X',
  'theme.discoveredAttack': 'Ataques a la descubierta',
  'theme.deflection': 'Desviación',
  'theme.sacrifice': 'Sacrificios',
  'theme.hangingPiece': 'Piezas colgadas',
  'theme.endgame': 'Finales',
  'theme.promotion': 'Coronación',

  'puzzles.stormScore': '{solved} resueltos · quedan {left} · mejor {best}',
  'puzzles.streakScore': '{solved} seguidos · mejor {best}',
  'puzzles.trainScore': 'Tu elo de ejercicios es {rating} · solo en este dispositivo',
  'puzzles.oneDayRun': '{days} día seguido',
  'puzzles.dayRun': '{days} días seguidos',
  'puzzles.startARun': 'Resuélvelo para empezar una racha de días',
  'puzzles.noPuzzle': 'No se ha podido cargar ningún ejercicio. Es fallo nuestro, no tuyo.',
  'puzzles.themesAndRating': '{themes} · elo {rating}',
  'puzzles.ratingOnly': 'Elo {rating}',
  'puzzles.watchTheirMove': 'Mira su jugada…',
  'puzzles.whiteToPlay': 'Juegan blancas. Encuentra la mejor jugada.',
  'puzzles.blackToPlay': 'Juegan negras. Encuentra la mejor jugada.',
  'puzzles.rightKeepGoing': 'Correcto. Sigue así.',
  'puzzles.solved': 'Resuelto.',
  'puzzles.solvedToday': 'Resuelto. El de hoy está hecho.',
  'puzzles.trainOnMore': 'Entrenar con más ejercicios',
  'puzzles.runEnds': 'Esa no. La racha termina en {solved}.',
  'puzzles.anotherRun': 'Empezar otra racha',
  'puzzles.stormPenalty': 'Esa no — {seconds} segundos.',
  'puzzles.tryAgain': 'Esa no. Inténtalo otra vez, o mira la solución.',
  'puzzles.skip': 'Saltarse este',
  'puzzles.showAnswer': 'Ver la solución',
  'puzzles.theMoveWas': 'La jugada era {move}.',
  'puzzles.thatIsTheLine': 'Esa es la línea.',
  'puzzles.timeUp': 'Se acabó el tiempo. {solved} resueltos.',
  'puzzles.runItAgain': 'Otra vez',

  'pool.allClaimed':
    'Hoy ya se han reclamado todas las recompensas. El fondo se nutre de las recompensas de staking, así que se rellena mañana en vez de agotarse.',
  'pool.notFunded': 'El fondo de ejercicios aún no tiene dinero. Resolver sigue contando para tu racha.',
  'pool.thereIs': 'Hay {amount} en el fondo para el ejercicio de hoy.',
  'pool.claim': 'Reclamar {amount}',
  'pool.claiming': 'Reclamando…',
  'pool.needsWallet':
    'La recompensa se paga en NIM, así que necesita una cartera donde llegar. Abre esto en Nimiq Pay y reclamarla es un toque.',
  'pool.deviceReason': 'Para que el fondo distinga una reclamación de otra',
  'pool.sent': 'Se han enviado {amount} a tu cartera. La transacción dice de qué ejercicio se trata.',
  'pool.recorded':
    '{amount} son tuyos y la reclamación está registrada, pero la transacción aún no ha salido. Se enviará — no se pierde nada.',

  'common.backToBoard': 'Volver al tablero',

  'settings.title': 'Ajustes',
  'settings.done': 'Listo',
  'settings.opponent': 'Rival',
  'settings.opponentHelp': 'Cambiar esto empieza una partida nueva.',
  'settings.board': 'El tablero',
  'settings.boardColours': 'Colores del tablero',
  'settings.wood': 'Madera',
  'settings.slate': 'Pizarra',
  'settings.sea': 'Mar',
  'settings.moveDots': 'Puntos de jugada',
  'settings.moveDotsHelp': 'Muestra adónde puede ir la pieza que levantas.',
  'settings.coordinates': 'Coordenadas',
  'settings.coordinatesHelp': 'Letras de columna y números de fila en el borde.',
  'settings.autoQueen': 'Coronar siempre dama',
  'settings.autoQueenHelp': 'Desactívalo para elegir torre, alfil o caballo.',
  'settings.zen': 'Zen',
  'settings.zenHelp': 'Solo el tablero. Nada más en la pantalla.',
  'settings.blindfold': 'A ciegas',
  'settings.blindfoldHelp':
    'Oculta las piezas y juega desde la lista de jugadas. Es tan difícil como suena.',
  'settings.feedback': 'Respuesta',
  'settings.sound': 'Sonido',
  'settings.soundHelp': 'Jugada, captura, jaque y final de partida.',
  'settings.haptics': 'Vibración',
  'settings.hapticsHelp': 'Una vibración corta en los móviles que la admiten.',
  'settings.language': 'Idioma',
  'settings.languageHelp': 'Sigue a Nimiq Pay salvo que elijas uno.',
  'settings.languageAuto': 'Automático',

  'level.looksGood': 'Juega lo primero que le parece bien',
  'level.oneAhead': 'Piensa una o dos jugadas por delante',
  'level.simpleTactics': 'Ve casi todas las tácticas sencillas',
  'level.punishes': 'Castiga una pieza suelta',

  'result.checkmate': 'Jaque mate',
  'result.stalemate': 'Rey ahogado — tablas',
  'result.insufficient': 'Material insuficiente para dar mate — tablas',
  'result.fiftyMove': 'Cincuenta jugadas sin captura ni movimiento de peón — tablas',
  'result.repetition': 'La misma posición cinco veces — tablas',
  'result.gameOver': 'Fin de la partida',
  'result.whiteWins': ' — ganan las blancas',
  'result.blackWins': ' — ganan las negras',
  'result.check': ' — jaque',

  'record.puzzleRating': 'Puntuación de problemas',
  'puzzles.signing': 'Firmando esta ronda…',
  'puzzles.seeRecord': 'Ver tu historial',
  'puzzles.makeCount': 'Que mis rondas cuenten',
  'puzzles.loading': 'Cargando problemas…',
  'puzzles.dailyDoneNote': 'El problema de hoy ya está resuelto. Vuelve mañana.',
  'puzzles.trainMore': 'Entrenar con más problemas',
  'puzzles.backToBoard': 'Volver al tablero',
  'game.claim': 'Una puntuación de ajedrez que nadie puede quitarte. La firman los dos jugadores, no nosotros.',
  'game.resign': 'Abandonar',
  'game.resignAgain': 'Toca otra vez para abandonar',
  'game.takeback': 'Deshacer',
  'game.backToStart': 'De vuelta al principio. Te toca.',
  'game.takenBack': 'Deshecha. Te toca.',
  'game.flip': 'Girar el tablero',
  'game.newGame': 'Partida nueva',
  'game.playFriend': 'Jugar con un amigo',
  'game.leaveZen': 'Salir del modo zen, o cambiar los ajustes',
  'game.resignedBlackWins': 'Has abandonado — ganan las negras',
  'game.resignedWhiteWins': 'Has abandonado — ganan las blancas',
  'game.rematch': 'La revancha',
  'game.review': 'Ver dónde se torció',
  'game.youVs': 'Tú contra {bot} · {moves} jugadas',
  'game.seeRecord': 'Ver tu historial',
  'game.yourMoveAsWhite': 'Te toca. Llevas blancas, contra {bot}.',
  'game.botIsWhite': '{bot} lleva blancas. Le toca.',
  'game.youFlagged': 'Se te ha acabado el tiempo.',
  'game.theyFlagged': 'Se le ha acabado el tiempo — ganas.',
  'game.clock': 'Reloj',
  'game.clockHelp': 'Cambiar esto empieza una partida nueva.',
  'game.newGameAgainst': 'Partida nueva contra {bot}.',

  'sign.button': 'Firma el resultado para que cuente',
  'sign.waiting': 'Esperando a tu cartera…',
  'sign.whatWasSigned': 'Qué se ha firmado',
  'sign.done': 'Firmado. Este resultado es tuyo, y cualquiera puede comprobarlo sin nosotros.',
  'sign.demoDone':
    'Firmado con la cartera de prueba. La firma es real y se verifica — pero su clave está publicada en nuestro código, así que demuestra el mecanismo, no que seas tú.',
  'sign.needsNimiqPay':
    'La firma ocurre dentro de Nimiq Pay. Abre esto ahí y el resultado pasa a ser tuyo.',
  'sign.invitation':
    'Firma el resultado y pasa a ser tuyo — un registro que nadie puede revocar, comprobable sin nosotros.',

  'live.checkmate': 'Jaque mate',
  'live.resignation': 'Abandono',
  'live.timeout': 'Tiempo',
  'live.stalemate': 'Rey ahogado',
  'live.insufficient': 'Material insuficiente para dar mate',
  'live.repetition': 'Triple repetición',
  'live.fiftyMove': 'Regla de las cincuenta jugadas',
  'live.agreement': 'Tablas acordadas',
  'live.reasonDraw': '{reason} — tablas',
  'live.reasonYouWin': '{reason} — ganas',
  'live.reasonYouLose': '{reason} — pierdes',
  'live.reasonYouWinStop': '{reason} — ganas.',
  'live.reasonYouLoseStop': '{reason} — pierdes.',
  'live.waitingForSomebody': 'Esperando a que alguien abra tu enlace.',
  'live.watching': 'Estás viendo esta partida.',
  'live.yourMove': 'Te toca.',
  'live.theirMove': 'Le toca.',
  'live.sendThisLink': 'Envía este enlace a quien quieras que juegue',
  'live.linkLabel': 'El enlace a esta partida',
  'live.copy': 'Copiar',
  'live.copied': 'Copiado',
  'live.pressToCopy': 'Pulsa para copiar',
  'live.claimWin': 'Reclamar la victoria por tiempo',
  'live.offerDraw': 'Ofrecer tablas',
  'live.sign': 'Firmar el resultado',
  'live.signed': 'Firmado',
  'live.bothSignatures':
    'Las dos firmas hacen de esto un elo que nadie puede quitarte. Puedes firmar ahora; el otro jugador firmará cuando abra el enlace.',
  'live.gameTitle': '{white} contra {black} · {moves} jugadas',
  'live.theyWantAnother': 'Quiere otra partida — únete',
  'live.waitingForRematch': 'Esperando a que se una a tu revancha.',
  'live.playAgain': 'Jugar otra vez',
  'live.settingUp': 'Preparándola…',
  'live.noHeightYet':
    'La altura de bloque de esta partida aún no ha llegado, y un resultado necesita una para ordenarse frente a tus demás partidas. Espera un momento y firma otra vez — no se pierde nada.',
  'live.publicLink': 'Obtener un enlace que cualquiera puede comprobar',
  'live.trouble': 'Problemas para llegar a la partida. Seguimos intentándolo — no se pierde nada.',
  'live.opening': 'Abriendo la partida…',
  'live.watchOnly':
    'Puedes ver esta partida. Para jugar, ábrela en Nimiq Pay para que tenga una dirección con la que firmar.',
  'live.alreadyTwo': 'Esta partida ya tiene dos jugadores. Estás de espectador.',
  'live.expired': 'Esa partida ha terminado o ha caducado. Los enlaces duran un día.',
  'live.leaveWarning':
    '¿Salir de esta partida? Tu reloj sigue corriendo, y tu rival podrá reclamar la victoria cuando se agote.',
  'live.stay': 'Quedarme',
  'live.leaveAnyway': 'Salir igualmente',

  'fail.offline':
    'No se ha podido llegar a la partida. Revisa tu conexión — no se pierde nada, y seguirá donde lo dejaste.',
  'fail.noGame': 'Esa partida ha terminado o ha caducado. Los enlaces duran un día.',
  'fail.gameFull': 'Ya hay dos personas jugando esta. Puedes verla.',
  'fail.notYourTurn': 'Le toca a la otra persona. Tu tablero se pondrá al día en un momento.',
  'fail.notAPlayer': 'Estás viendo esta partida, no jugándola.',
  'fail.notStarted': 'Nadie ha abierto tu enlace todavía, así que no hay contra quién mover.',
  'fail.gameOver': 'Esa partida ya ha terminado.',
  'fail.illegalMove': 'Esa jugada no es legal en esta posición. El tablero ha vuelto a su sitio.',
  'fail.stale':
    'La partida avanzó mientras eso iba de camino. Tu tablero ya está al día — inténtalo otra vez.',
  'fail.notFlagged': 'Su reloj todavía no se ha agotado.',
  'fail.ownFlag': 'El reloj que se ha agotado es el tuyo, no el suyo.',
  'fail.notOver': 'Una partida solo se puede firmar cuando ha terminado.',
  'fail.serverError':
    'Algo ha fallado por nuestra parte. Tu partida está a salvo — está en el servidor, y la próxima comprobación la encontrará.',
  'fail.tooMany':
    'Han sido muchas peticiones de golpe. Espera unos segundos — tu partida está a salvo y no se ha perdido nada.',
  'fail.tooLarge': 'Esa petición era demasiado grande para enviarla. Esta es culpa nuestra, no tuya.',
  'fail.declined': 'No has firmado. No se ha registrado nada, y puedes firmar cuando quieras.',
  'fail.cancelled': 'Cancelado. No se ha perdido nada.',
  'fail.badSignature':
    'Tu cartera ha devuelto una firma que esta aplicación no ha sabido leer. Avísanos, por favor — es fallo nuestro, no tuyo.',
  'fail.noStorage':
    'Este navegador no deja que la aplicación guarde nada. Todo sigue funcionando por ahora, pero se perderá al cerrar la pestaña.',
  'fail.refused': 'Este navegador ha rechazado eso. No se ha perdido nada.',
  'fail.chunk': 'Una parte de la aplicación no se ha podido cargar. Recarga la página y volverá.',
  'fail.network': 'Tu dispositivo no ha podido llegar a la red. No se ha perdido nada — inténtalo en un momento.',
  'fail.notConfirmed': 'No lo has confirmado. No ha pasado nada.',
  'fail.syncing': 'Nimiq Pay todavía se está poniendo al día con la cadena. Dale unos segundos.',
  'fail.somethingWith': 'Algo ha fallado: {detail}',
  'fail.something': 'Algo ha fallado. No se ha firmado nada y no se ha perdido nada.',
  'fail.noWalletSign': 'La firma ocurre dentro de Nimiq Pay. Abre esto ahí.',
  'fail.noAddress': 'La cartera no ha devuelto ninguna dirección.',
  'fail.phoneNetwork': 'Tu móvil no ha podido llegar a la red. No se ha perdido nada — inténtalo en un momento.',
  'fail.somethingSigning': 'Algo ha fallado. No se ha firmado nada.',
  'fail.timeout': '{step} — Nimiq Pay no ha respondido. Abre la cartera e inténtalo otra vez.',

  'wallet.sharingAddress': 'Compartiendo tu dirección',
  'wallet.signing': 'Firmando',
  'wallet.checkingSync': 'Comprobando que la cartera está al día',
  'wallet.readingHeight': 'Leyendo la altura de la cadena',
  'wallet.identifyingDevice': 'Identificando este dispositivo',

  'record.allPublished':
    'Todas las partidas de aquí se firmaron con una clave publicada en nuestro código — la cartera de prueba, o el bot. Las firmas se verifican, y cualquiera puede crear más, así que esto enseña cómo se llega al número y no de quién es.',
  'record.somePublished':
    '{published} de estas {total} partidas se firmaron con una clave publicada en nuestro código — la cartera de prueba, o el bot. Esas firmas se verifican, y cualquiera puede crear más.',
  'record.title': 'Historial',
  'record.noRatedGames': 'Todavía no hay partidas puntuables',
  'record.oneRatedGame': '{games} partida puntuable',
  'record.ratedGames': '{games} partidas puntuables',
  'record.oneOpponent': '{count} rival distinto',
  'record.opponents': '{count} rivales distintos',
  'record.provisional': 'Provisional hasta que hayan firmado {needed} rivales distintos. Llevas {so_far}.',
  'record.recompute': 'Recalcularlo aquí',
  'record.recomputeNote':
    'Vuelve a derivar cada elo de abajo en este navegador, solo a partir de las firmas. No se le pide nada a nuestro servidor.',
  'record.checking': 'Comprobando cada firma…',
  'record.checkedOne': 'Comprobada {checked} partida firmada aquí, en este navegador.',
  'record.checkedMany': 'Comprobadas {checked} partidas firmadas aquí, en este navegador.',
  'record.noneRate': 'Ninguna puntúa, así que el elo se queda en su valor inicial.',
  'record.someRate': '{games} de ellas puntúan.',
  'record.agrees': 'Este navegador ha llegado a {reached} — el mismo número que esta página.',
  'record.disagrees':
    'Este navegador ha llegado a {reached} y esta página dice {shown}. Si no coinciden, esta página está equivocada.',
  'record.leftOutUnsigned': '{count} sin firmar todavía por los dos jugadores',
  'record.leftOutInvalid': '{count} no se han verificado',
  'record.leftOut': 'Quedan fuera: {detail}.',
  'record.empty': 'Todavía no hay partidas firmadas en esta cartera.',
  'record.emptyNote':
    'Eso no es ni buena ni mala señal — es una cartera sin historial. Juega una partida y firma el resultado.',
  'record.everyGame': 'Todas las partidas, en el orden en que cuentan',
  'record.won': 'Ganada',
  'record.lost': 'Perdida',
  'record.drew': 'Tablas',
  'record.casual': 'Amistosa — nunca puntúa',
  'record.tooShort': 'Menos de {moves} jugadas — registrada, no puntuable',
  'record.farmed': 'Demasiadas partidas contra este rival — ya no mueve ningún elo',
  'record.gameLine': '{termination} · {moves} jugadas · bloque {block}',
  'record.footer':
    'Todos los números de aquí se derivan de firmas que hicieron los dos jugadores. Nadie puede editarlo — ni la persona de quien habla, ni nosotros.',

  'judge.best': 'La mejor',
  'judge.bests': 'mejores jugadas',
  'judge.good': 'Buena',
  'judge.goods': 'buenas jugadas',
  'judge.inaccuracy': 'Imprecisión',
  'judge.inaccuracies': 'imprecisiones',
  'judge.mistake': 'Error',
  'judge.mistakes': 'errores',
  'judge.blunder': 'Error grave',
  'judge.blunders': 'errores graves',

  'study.title': 'Estudiar una partida',
  'study.note':
    'Pega una partida en PGN — de Lichess, Chess.com, un torneo, de donde sea — o estudia la que acabas de jugar. Aquí no se firma nada y nada afecta a tu elo.',
  'study.handedNote':
    'La partida que acabas de jugar. Aquí no se firma nada y nada afecta a tu elo — esto es para mirarlo.',
  'study.pasteLabel': 'Pega una partida en PGN',
  'study.open': 'Abrirla',
  'study.analyse': 'Analizar esta partida',
  'study.looking': 'Mirando la partida…',
  'study.lookingProgress': 'Mirando la partida… {done} de {total} jugadas.',
  'study.wasBest': '{number} {san} — la mejor jugada aquí.',
  'study.wasGood': '{number} {san} — una buena jugada.',
  'study.wasWorse': '{number} {san} — {label}. {better} era mejor, por {lost} puntos de probabilidad de ganar.',
  'study.acpl': '{acpl} centipeones perdidos por jugada',
  'study.whiteAhead': 'Van mejor las blancas — {percent} por ciento',
  'study.blackAhead': 'Van mejor las negras — {percent} por ciento',
  'study.nothingToComplain': 'nada que reprochar',
  'study.caveat':
    'Revisada por el motor propio de esta aplicación, funcionando en tu dispositivo — nivel de club, no Stockfish. Encontrará los errores graves de una partida corriente y no le llevará la contraria a un gran maestro.',
  'study.reviewed': 'La partida está revisada. Recórrela para ver el juicio de cada jugada.',
  'study.analysisFailed': 'El análisis se ha detenido: {detail}. Es fallo nuestro — avísanos, por favor.',
  'study.playersVs': '{white} contra {black}',
  'study.animported': 'Una partida importada',
  'study.heading': '{players} · {moves} jugadas',
  'study.loaded': '{plies} jugadas cargadas. Recórrelas con las flechas.',

  'cert.title': 'Una partida firmada',
  'cert.fetching': 'Buscando la partida…',
  'cert.stillPlaying': 'Esa partida se está jugando todavía. El certificado aparece cuando termina.',
  'cert.unreconstructable': 'Esa partida no se puede reconstruir, así que aquí no se puede comprobar nada.',
  'cert.onlyOne': 'De momento solo ha firmado un jugador. Será un registro cuando hayan firmado los dos.',
  'cert.verified':
    'Los dos jugadores firmaron este resultado, y este navegador acaba de comprobar ambas firmas.',
  'cert.bad': 'Estas firmas no cuadran. No te creas este resultado.',
  'cert.nothingAsked':
    'No se le ha pedido nada a nuestro servidor para llegar a esa conclusión más allá de la propia partida — las firmas se han verificado aquí, en tu dispositivo, contra el texto exacto que firmaron los dos jugadores.',
  'cert.checkFailed': 'La comprobación ha fallado: {reason}.',
  'cert.unknown': 'desconocido',
  'cert.winnersRecord': 'Ver el historial del ganador',
  'cert.playYourself': 'Juega tú una partida',
  'cert.signed': 'firmada',
  'cert.notSignedYet': 'sin firmar todavía',

  'certificate.abandoned': 'Abandonada',
  'certificate.cannotDraw': 'Este navegador no puede dibujar un certificado.',
  'certificate.noPicture': 'No se ha podido crear la imagen.',
  'certificate.whiteWins': 'Ganan las blancas',
  'certificate.blackWins': 'Ganan las negras',
  'certificate.drawn': 'Tablas',
  'certificate.rated': 'puntuable',
  'certificate.casual': 'amistosa',
  'certificate.summary': '{reason} · {moves} jugadas · {kind}',
  'certificate.bothSigned': 'Los dos jugadores firmaron este resultado',
  'certificate.evidence':
    'Bloque de Nimiq {block} · partida {game}… · cualquiera puede comprobarlo en {where}',
  'certificate.signatureOf': 'Firma de {side}',
  'certificate.tagline': 'Un elo que nadie ha emitido y nadie puede revocar.',

  'share.asPicture': 'Compartir como imagen',
  'share.asPgn': 'Guardar como PGN',
  'share.sent': 'Enviado.',
  'share.savedPicture': 'Guardado como imagen.',
  'share.savedPgn': 'Guardado como PGN, que leen todos los programas de ajedrez.',
  'share.notOnDevice': 'Esa partida ya no está en este dispositivo.',
  'share.didNotWork': 'Eso no ha funcionado en este dispositivo. La partida está a salvo igualmente.',

  'sign.notOver': 'Esa partida no ha terminado todavía.',
  'sign.syncing':
    'Nimiq Pay todavía se está poniendo al día con la cadena. Dale unos segundos y firma otra vez.',
  'sign.noHeight':
    'Nimiq Pay no ha podido leer la altura de la cadena ahora mismo, y una partida necesita una para ordenarse. Inténtalo en un momento.',
  'sign.notYourGame': 'Esta cartera no jugó esa partida, así que aquí no hay nada que pueda firmar.',

  'api.offline': 'No se ha podido llegar a la partida. Revisa tu conexión.',
  'api.something': 'Algo ha fallado.',
  'api.badShape':
    'El servidor ha enviado algo que esta aplicación no ha sabido leer. Es fallo nuestro, no tuyo — tu partida está a salvo en el servidor.',
  'poolApi.offline': 'No se ha podido llegar al fondo.',
  'poolApi.refused': 'No se ha podido hacer esa reclamación.',
  'poolApi.alreadyClaimed':
    'Ya has reclamado hoy. El ejercicio cambia a medianoche, y esto también.',
  'poolApi.deviceClaimed':
    'Este dispositivo ya ha reclamado hoy — uno por dispositivo, que es lo que impide que un script vacíe el fondo.',
  'poolApi.notFunded':
    'El fondo no tiene dinero ahora mismo, así que no hay nada que reclamar. Resolver sigue contando para tu racha.',
  'poolApi.needsNimiqPay':
    'Reclamar necesita Nimiq Pay, que es lo que le dice al fondo que dos reclamaciones vienen de dos personas distintas.',
  'poolApi.unreachable':
    'No se ha podido llegar al fondo. Tu solución está a salvo — inténtalo otra vez en un momento.',

  'send.needsNimiqPay': 'Enviar NIM ocurre dentro de Nimiq Pay. Abre esto ahí.',
  'send.memoTooLong': 'Ese mensaje es demasiado largo para una transacción de Nimiq. Esto es fallo nuestro.',
  'send.badAmount': 'Esa no es una cantidad que se pueda enviar.',
  'send.waiting': 'Esperando a tu cartera',
  'send.declined': 'No se ha enviado nada. Tus NIM siguen donde estaban.',
  'send.failed': 'No se ha podido enviar. No ha salido nada de tu cartera.',
  'send.tip': 'Envíale {amount} NIM',
  'send.tipTitle': '¿Buena partida?',
  'send.tipNote':
    'Envíale NIM directamente desde tu cartera. No pasa por nosotros, y la transacción dice de qué partida se trata.',
  'send.tipSent': 'Enviado. {amount} NIM han ido de tu cartera a la suya.',
  'send.poolTitle': 'Devuelve algo',
  'send.poolNote':
    'El fondo paga a un desconocido por resolver el ejercicio del día. Cualquiera puede añadir, y cada pago que hace está en la cadena con el ejercicio escrito dentro.',
  'send.poolAdd': 'Añadir {amount} NIM al fondo',
  'send.poolSent': 'Enviado. {amount} NIM están en el fondo para quien resuelva el próximo.',
  'send.sending': 'Esperando a tu cartera…',

  'app.broke': 'Algo se ha roto',

  /* ---------------------------------------------------------------- the portable record */
  'record.take': 'Ll\u00e9vate tu historial',
  'record.takeNote':
    'Un archivo con cada partida y cada tanda de problemas firmadas en este dispositivo. Cualquiera puede comprobarlo sin esta web y sin preguntarnos nada.',
  'record.takeButton': 'Guardar mi historial',
  'record.takeEmpty': 'Todav\u00eda no hay nada firmado en este dispositivo.',
  'record.recordSent': 'Enviado \u2014 {games} partidas y {runs} tandas de problemas.',
  'record.recordSaved': 'Guardado \u2014 {games} partidas y {runs} tandas de problemas.',
  'record.recordSkipped': '{count} fuera: sin firmar por ambas partes, o de la otra red.',

  /* ---------------------------------------------------------------- the verify screen */
  'verify.title': 'Comprobar un historial',
  'verify.intro':
    '\u00bfAlguien te ha enviado un historial de Scoresheet? \u00c1brelo aqu\u00ed. Tu navegador comprueba cada firma y calcula la puntuaci\u00f3n por su cuenta. No se sube nada, y esta p\u00e1gina no necesita nuestro servidor.',
  'verify.choose': 'Elegir un archivo',
  'verify.checking': 'Comprobando cada firma\u2026',
  'verify.unreadable': 'No se ha podido leer ese archivo.',
  'verify.notARecord': 'Eso no es un historial de Scoresheet.',
  'verify.oneGame': '1 partida comprobada, y {runs} tandas de problemas.',
  'verify.manyGames': '{games} partidas comprobadas, y {runs} tandas de problemas.',
  'verify.rating': 'Puntuaci\u00f3n {rating}, de {games} partidas puntuadas contra {opponents} personas distintas.',
  'verify.noneRate': 'Ninguna de estas partidas puntu\u00faa, as\u00ed que no hay puntuaci\u00f3n que comprobar.',
  'verify.provisional': 'Provisional: una puntuaci\u00f3n se asienta tras diez rivales distintos.',
  'verify.puzzleRating': 'Puntuaci\u00f3n de problemas {rating}.',
  'verify.findings': 'Lo que no ha cuadrado',
  'verify.badSignature': 'Partida {id}: la firma de {side} no coincide.',
  'verify.notTheirs': 'Se ha dejado fuera una partida que pertenece a otra persona.',
  'verify.wrongChain': 'Se ha dejado fuera una partida de la otra red.',
  'verify.malformed': 'No se ha podido leer un registro: {detail}',
  'verify.gameRootMismatch': 'Las partidas no dan la huella que este historial declara. Se ha a\u00f1adido o quitado algo despu\u00e9s.',
  'verify.runRootMismatch': 'Las tandas de problemas no dan la huella que este historial declara.',
  'verify.anchorBefore': 'Este historial dice haberse sellado en la cadena antes de una de sus propias partidas.',
  'verify.anchored': 'Sellado en la cadena de Nimiq, despu\u00e9s de la \u00faltima partida que contiene.',
  'verify.caveat':
    'Esto demuestra que estas partidas ocurrieron y no se han cambiado. No demuestra que la lista est\u00e9 completa \u2014 cualquiera puede omitir una derrota de un historial que publica \u00e9l mismo.',

  'study.tryAgain': 'Int\u00e9ntalo t\u00fa',
  'study.tryGiveUp': 'Mu\u00e9stramelo',
  'study.tryPrompt': 'Te toca. Encuentra algo mejor que lo que jugaste.',
  'study.tryThinking': 'Analizando\u2026',
  'study.tryFound': '{san}: eso es. Es lo que quer\u00eda el motor.',
  'study.tryBetter': '{san} es mejor que lo que jugaste, aunque no es lo mejor. Cuesta {lost} puntos en su lugar.',
  'study.tryNo': '{san} cuesta {lost} puntos: no mejora tu jugada. Prueba otra.',
  'study.tryUnknown': 'El motor no ha respondido a tiempo, as\u00ed que esta queda sin juzgar.',

  'study.trainThis': 'Entrenar esto',
  'study.trainChecking': 'Comprobando si esto da un problema justo…',
  'study.trainAdded': 'Añadido a tu entrenamiento. Volverás a ver esta posición.',
  'study.trainAlready': 'Esta ya está en tu entrenamiento.',
  'study.trainNotUnique': 'No añadido: aquí hay más de una buena jugada, no sería un problema justo.',
  'study.trainNotSuitable': 'No añadido: la mejor jugada aquí no es algo que un problema pueda pedir.',
  'study.trainNotSound': 'No añadido: una mirada más larga no coincidió con la primera.',
  'study.trainUnknown': 'El motor no respondió a tiempo, así que no se añadió.',
  'puzzles.mine': 'Tus propios errores',
  'puzzles.mineDetail': '{count} esperando. Posiciones que fallaste, las peores primero.',
  'puzzles.mineDone': 'Eso es todo. Has repasado todos los errores que guardaste.',

  /* ---------------------------------------------------------------- tournaments */
  'lobby.tourneyTitle': 'Organizar un torneo',
  'lobby.tourneyNote': 'Todos contra todos, o suizo por encima de ocho. Recibes un enlace para enviar a los jugadores.',
  'lobby.seats': 'Jugadores',
  'lobby.seats4': 'Cuatro',
  'lobby.seats4Detail': 'Seis partidas, una ronda cada una',
  'lobby.seats6': 'Seis',
  'lobby.seats6Detail': 'Quince partidas',
  'lobby.seats8': 'Ocho',
  'lobby.seats8Detail': 'Todos contra todos',
  'lobby.seats12': 'Doce',
  'lobby.seats12Detail': 'Suizo, cinco rondas',
  'lobby.hold': 'Organizar un torneo',
  'lobby.tourneyName': 'Torneo',
  'tourney.title': 'Torneo',
  'tourney.loading': 'Cargando el torneo\u2026',
  'tourney.notFound': 'No hay ning\u00fan torneo con ese enlace.',
  'tourney.unavailable': 'Ese torneo no se ha podido cargar ahora mismo.',
  'tourney.open': 'Abierto \u2014 {entrants} de {seats} plazas ocupadas.',
  'tourney.running': 'En juego \u2014 {entrants} jugadores.',
  'tourney.finished': 'Terminado \u2014 {entrants} jugadores.',
  'tourney.agrees': 'Este navegador ha calculado la tabla por su cuenta, a partir de las partidas, y ha llegado al mismo orden.',
  'tourney.disagrees': 'Este navegador calcula otra tabla con estas partidas. Algo no cuadra.',
  'tourney.standings': 'Clasificaci\u00f3n',
  'tourney.games': 'Partidas',
  'tourney.round': 'Ronda {round}',
  'tourney.toPlay': 'por jugar',
  'tourney.prize': '{nim} NIM',
  'tourney.caveat': 'Cada partida de arriba se verificó en este navegador, contra las dos firmas que lleva. El orden se deduce de esas partidas, y acabas de verlo calcular.',
  'tourney.agreesSigned': 'Este navegador comprobó él mismo las {games} partidas firmadas y obtuvo la misma tabla, sin preguntarnos nada.',
  'tourney.dropped': '{games} partidas enviadas no se pudieron verificar y quedaron fuera de la tabla.',
  'tourney.caveatUnchecked': 'El orden se deduce de estos resultados, y acabas de comprobarlo tú mismo. Si estos son los resultados es otra cuestión, y cada partida la responde en su propio certificado.',
  'tourney.join': 'Apuntarme a este torneo',
  'tourney.joinFailed': 'No se pudo. Puede que ya no queden plazas.',
  'tourney.yours': 'Tus partidas',
  'tourney.playThem': 'aún sin jugar',
  'tourney.report': 'Enviar la partida',
  'tourney.reportFailed': 'Esa partida no se aceptó. Tiene que estar firmada por los dos.',
  'tourney.back': 'Volver',
};
