/**
 * Français.
 *
 * Written against `en.ts`, which owns the key set — `i18n.test.ts` fails if a key here is missing or
 * invented. Chess vocabulary is the standard French set (*échec et mat*, *pat*, *nulle*, *les
 * Blancs*, *les Noirs*, *fou*, *cavalier*, *tour*, *dame*), and the register matches the English:
 * plain, about the game rather than the software, and never blaming the person reading it.
 *
 * Addressed as **tu** throughout, and the French typographic space before `?` and `:` is kept —
 * a narrow no-break space, which is what makes a sentence read as written in French rather than
 * translated into it.
 */

import type { en } from './en.ts';

export const fr: Record<keyof typeof en, string> = {
  'nav.sections': 'Sections',
  'nav.play': 'Jouer',
  'nav.train': 'S’entraîner',
  'nav.you': 'Toi',
  'nav.noRecord':
    'Ton palmarès apparaît ici dès qu’une partie est signée. Termines-en une et signe le résultat — c’est une seule pression.',

  'moves.label': 'Coups',
  'moves.empty': 'Les coups apparaissent ici au fur et à mesure.',
  'moves.viewingEarlier': 'Tu regardes une position antérieure',
  'moves.toStart': 'Aller au début',
  'moves.back': 'Coup précédent',
  'moves.forward': 'Coup suivant',
  'moves.toLive': 'Revenir à la position actuelle',
  'moves.namedAfter': '{eco} · nommée après {plies} coups',
  'moves.namedAfterOne': '{eco} · nommée après {plies} coup',

  'board.label': 'Échiquier',
  'board.square': '{square}, {piece}',
  'board.empty': 'vide',
  'board.promote': 'Choisis une pièce pour la promotion',

  'piece.pawn': 'pion',
  'piece.knight': 'cavalier',
  'piece.bishop': 'fou',
  'piece.rook': 'tour',
  'piece.queen': 'dame',
  'piece.king': 'roi',
  'piece.piece': 'pièce',

  'lobby.title': 'Jouer contre un ami',
  'lobby.note':
    'Tu reçois un lien. Celui qui l’ouvre prend l’autre camp — sans compte et sans portefeuille.',
  'lobby.time': 'Cadence',
  'lobby.youPlay': 'Tu joues',
  'lobby.make': 'Créer le lien',
  'lobby.making': 'Création…',
  'lobby.study': 'Ou étudier une partie depuis un PGN',
  'lobby.needsWallet':
    'Une partie contre quelqu’un a besoin d’un portefeuille pour signer le résultat. Ouvre ceci dans Nimiq Pay, ou joue contre le bot — ça ne demande rien du tout.',

  'time.bullet': 'Bullet',
  'time.bulletDetail': '1 minute chacun',
  'time.blitz': 'Blitz',
  'time.blitzDetail': '3 minutes, 2 secondes par coup',
  'time.rapid': 'Rapide',
  'time.rapidDetail': '10 minutes, 5 secondes par coup',
  'time.unlimited': 'Sans pendule',
  'time.unlimitedDetail': 'Prends tout le temps que tu veux',

  'colour.random': 'Au hasard',
  'colour.randomDetail': 'Comme d’habitude',
  'colour.white': 'Les Blancs',
  'colour.whiteDetail': 'Tu joues en premier',
  'colour.black': 'Les Noirs',
  'colour.blackDetail': 'L’autre joue en premier',

  'today.title': 'Aujourd’hui',
  'today.daily': 'Résoudre le problème du jour',
  'today.game': 'Jouer une partie',
  'today.win': 'En gagner une',
  'today.done': 'fait',
  'today.notYet': 'pas encore',

  'puzzles.title': 'Problèmes',
  'puzzles.rating': 'classement aux problèmes',
  'puzzles.dayInARow': 'jour d’affilée',
  'puzzles.daysInARow': 'jours d’affilée',
  'puzzles.bestStreak': 'meilleure série',
  'puzzles.bestStorm': 'meilleure tempête',
  'puzzles.note':
    'Ces chiffres vivent sur cet appareil et personne ne les signe. Ton classement sur la page de palmarès, c’est l’inverse : deux signatures, et personne ne peut te l’enlever.',
  'puzzles.daily': 'Problème du jour',
  'puzzles.dailyDone': 'Le problème du jour — fait',
  'puzzles.dailyDetail': 'Le même problème que tout le monde aujourd’hui.',
  'puzzles.train': 'S’entraîner',
  'puzzles.trainDetail': 'Sans fin, et il trouve ton niveau en cours de route.',
  'puzzles.storm': 'Tempête',
  'puzzles.stormDetail': 'Trois minutes. Autant que tu peux.',
  'puzzles.streak': 'Série',
  'puzzles.streakDetail': 'Sans pendule. Elle s’arrête à la première erreur.',
  'puzzles.oneIdea': 'Ou travailler une seule idée',
  'coords.title': 'Coordonnées',
  'coords.note':
    'Savoir où est une case sans compter est la compétence que tous les livres d’échecs supposent acquise. Trente secondes, autant que tu peux.',
  'coords.menuDetail': 'Trente secondes pour trouver le plus de cases possible.',
  'coords.mode': 'Mode',
  'coords.findSquare': 'Trouver la case',
  'coords.nameSquare': 'Nommer la case',
  'coords.playAs': 'Tu joues',
  'coords.showPieces': 'Afficher les pièces',
  'coords.start': 'Commencer',
  'coords.again': 'Recommencer',
  'coords.change': 'Changer les réglages',
  'coords.findThis': '{square}',
  'coords.nameThis': 'Nomme la case éclairée',
  'coords.thisSquare': 'la case à nommer',
  'coords.score': '{correct} justes · {left} secondes restantes',
  'coords.youScored': 'Tu as fait {score}.',
  'coords.average': 'Avec {side} : {average} en moyenne, record {best}',
  'coords.noAverage': 'Avec {side} : rien encore',

  'puzzles.credit': 'Problèmes issus de la base ouverte de Lichess, versée au domaine public.',

  'theme.mateIn1': 'Mat en 1',
  'theme.mateIn2': 'Mat en 2',
  'theme.backRankMate': 'Dernière rangée',
  'theme.fork': 'Fourchettes',
  'theme.pin': 'Clouages',
  'theme.skewer': 'Enfilades',
  'theme.discoveredAttack': 'Attaques à la découverte',
  'theme.deflection': 'Déviation',
  'theme.sacrifice': 'Sacrifices',
  'theme.hangingPiece': 'Pièces en prise',
  'theme.endgame': 'Finales',
  'theme.promotion': 'Promotion',

  'puzzles.stormScore': '{solved} résolus · {left} restant · record {best}',
  'puzzles.streakScore': '{solved} d’affilée · record {best}',
  'puzzles.trainScore': 'Ton classement aux problèmes est {rating} · sur cet appareil seulement',
  'puzzles.oneDayRun': '{days} jour d’affilée',
  'puzzles.dayRun': '{days} jours d’affilée',
  'puzzles.startARun': 'Résous-le pour lancer une série de jours',
  'puzzles.noPuzzle': 'Aucun problème n’a pu être chargé. C’est notre faute, pas la tienne.',
  'puzzles.themesAndRating': '{themes} · classé {rating}',
  'puzzles.ratingOnly': 'Classé {rating}',
  'puzzles.watchTheirMove': 'Regarde son coup…',
  'puzzles.whiteToPlay': 'Aux Blancs de jouer. Trouve le meilleur coup.',
  'puzzles.blackToPlay': 'Aux Noirs de jouer. Trouve le meilleur coup.',
  'puzzles.rightKeepGoing': 'Bien joué. Continue.',
  'puzzles.solved': 'Résolu.',
  'puzzles.solvedToday': 'Résolu. La journée est faite.',
  'puzzles.trainOnMore': 'S’entraîner sur d’autres problèmes',
  'puzzles.runEnds': 'Pas celui-là. La série s’arrête à {solved}.',
  'puzzles.anotherRun': 'Relancer une série',
  'puzzles.stormPenalty': 'Pas celui-là — {seconds} secondes.',
  'puzzles.tryAgain': 'Pas celui-là. Réessaie, ou regarde la solution.',
  'puzzles.skip': 'Passer celui-ci',
  'puzzles.showAnswer': 'Voir la solution',
  'puzzles.theMoveWas': 'Le coup était {move}.',
  'puzzles.thatIsTheLine': 'C’est la variante.',
  'puzzles.timeUp': 'Temps écoulé. {solved} résolus.',
  'puzzles.runItAgain': 'Recommencer',

  'pool.allClaimed':
    'Toutes les récompenses du jour ont été réclamées. La cagnotte est alimentée par les gains de staking : elle se remplit demain au lieu de s’épuiser.',
  'pool.notFunded': 'La cagnotte des problèmes n’est pas encore alimentée. Résoudre compte quand même pour ta série.',
  'pool.thereIs': 'Il y a {amount} dans la cagnotte pour le problème du jour.',
  'pool.claim': 'Réclamer {amount}',
  'pool.claiming': 'Réclamation…',
  'pool.needsWallet':
    'La récompense est versée en NIM : il lui faut un portefeuille où arriver. Ouvre ceci dans Nimiq Pay et la réclamation tient en une pression.',
  'pool.deviceReason': 'Pour que la cagnotte distingue une réclamation d’une autre',
  'pool.sent': '{amount} envoyés vers ton portefeuille. La transaction dit de quel problème il s’agit.',
  'pool.recorded':
    '{amount} sont à toi et la réclamation est enregistrée, mais la transaction n’est pas encore partie. Elle partira — rien n’est perdu.',

  'common.backToBoard': 'Revenir à l’échiquier',

  'settings.title': 'Réglages',
  'settings.done': 'Terminé',
  'settings.opponent': 'Adversaire',
  'settings.opponentHelp': 'Changer cela lance une nouvelle partie.',
  'settings.board': 'L’échiquier',
  'settings.boardColours': 'Couleurs de l’échiquier',
  'settings.wood': 'Bois',
  'settings.slate': 'Ardoise',
  'settings.sea': 'Mer',
  'settings.moveDots': 'Points de coup',
  'settings.moveDotsHelp': 'Montre où la pièce soulevée peut aller.',
  'settings.coordinates': 'Coordonnées',
  'settings.coordinatesHelp': 'Lettres de colonne et numéros de rangée sur le bord.',
  'settings.autoQueen': 'Toujours promouvoir en dame',
  'settings.autoQueenHelp': 'Désactive ceci pour choisir tour, fou ou cavalier.',
  'settings.zen': 'Zen',
  'settings.zenHelp': 'L’échiquier seul. Rien d’autre à l’écran.',
  'settings.blindfold': 'À l’aveugle',
  'settings.blindfoldHelp':
    'Cache les pièces et fait jouer depuis la liste des coups. C’est aussi difficile que ça en a l’air.',
  'settings.feedback': 'Retour',
  'settings.sound': 'Son',
  'settings.soundHelp': 'Coup, prise, échec et fin de partie.',
  'settings.haptics': 'Vibration',
  'settings.hapticsHelp': 'Une courte vibration sur les téléphones qui le permettent.',
  'settings.language': 'Langue',
  'settings.languageHelp': 'Suit Nimiq Pay tant que tu n’en choisis pas une.',
  'settings.languageAuto': 'Automatique',

  'level.looksGood': 'Joue la première chose qui a l’air bien',
  'level.oneAhead': 'Réfléchit un ou deux coups à l’avance',
  'level.simpleTactics': 'Voit la plupart des tactiques simples',
  'level.punishes': 'Punit une pièce en prise',

  'result.checkmate': 'Échec et mat',
  'result.stalemate': 'Pat — partie nulle',
  'result.insufficient': 'Matériel insuffisant pour mater — partie nulle',
  'result.fiftyMove': 'Cinquante coups sans prise ni coup de pion — partie nulle',
  'result.repetition': 'La même position cinq fois — partie nulle',
  'result.gameOver': 'Partie terminée',
  'result.whiteWins': ' — les Blancs gagnent',
  'result.blackWins': ' — les Noirs gagnent',
  'result.check': ' — échec',

  'record.puzzleRating': 'Classement aux problèmes',
  'puzzles.signing': 'Signature de cette série…',
  'puzzles.seeRecord': 'Voir votre historique',
  'puzzles.makeCount': 'Que mes séries comptent',
  'puzzles.loading': 'Chargement des problèmes…',
  'puzzles.dailyDoneNote': 'Le problème du jour est déjà fait. Revenez demain.',
  'puzzles.trainMore': 'S’entraîner sur d’autres problèmes',
  'puzzles.backToBoard': 'Retour à l’échiquier',
  'game.claim': 'Un classement d’échecs que personne ne peut vous retirer. Ce sont les deux joueurs qui signent le résultat, pas nous.',
  'game.resign': 'Abandonner',
  'game.resignAgain': 'Appuie encore pour abandonner',
  'game.takeback': 'Reprendre',
  'game.backToStart': 'Retour au début. À toi.',
  'game.takenBack': 'Coup repris. À toi.',
  'game.flip': 'Retourner l’échiquier',
  'game.newGame': 'Nouvelle partie',
  'game.playFriend': 'Jouer contre un ami',
  'game.leaveZen': 'Quitter le mode zen, ou changer les réglages',
  'game.resignedBlackWins': 'Tu as abandonné — les Noirs gagnent',
  'game.resignedWhiteWins': 'Tu as abandonné — les Blancs gagnent',
  'game.rematch': 'La revanche',
  'game.review': 'Voir où ça a dérapé',
  'game.youVs': 'Toi contre {bot} · {moves} coups',
  'game.seeRecord': 'Voir ton palmarès',
  'game.yourMoveAsWhite': 'À toi. Tu as les Blancs, contre {bot}.',
  'game.botIsWhite': '{bot} a les Blancs. À lui de jouer.',
  'game.youFlagged': 'Ton temps est écoulé.',
  'game.theyFlagged': 'Son temps est écoulé — tu gagnes.',
  'game.clock': 'Pendule',
  'game.clockHelp': 'Changer cela lance une nouvelle partie.',
  'game.newGameAgainst': 'Nouvelle partie contre {bot}.',

  'sign.button': 'Signe le résultat pour qu’il compte',
  'sign.waiting': 'En attente de ton portefeuille…',
  'sign.whatWasSigned': 'Ce qui a été signé',
  'sign.done': 'Signé. Ce résultat est à toi, et n’importe qui peut le vérifier sans nous.',
  'sign.demoDone':
    'Signé avec le portefeuille de démonstration. La signature est réelle et se vérifie — mais sa clé est publiée dans notre code, donc elle prouve le mécanisme, pas que c’est toi.',
  'sign.needsNimiqPay':
    'La signature se fait dans l’application Nimiq Pay. Ouvre ceci là-bas et le résultat devient le tien.',
  'sign.invitation':
    'Signe le résultat et il devient le tien — une trace que personne ne peut révoquer, vérifiable sans nous.',

  'live.checkmate': 'Échec et mat',
  'live.resignation': 'Abandon',
  'live.timeout': 'Temps',
  'live.stalemate': 'Pat',
  'live.insufficient': 'Matériel insuffisant pour mater',
  'live.repetition': 'Triple répétition',
  'live.fiftyMove': 'Règle des cinquante coups',
  'live.agreement': 'Nulle par accord',
  'live.reasonDraw': '{reason} — partie nulle',
  'live.reasonYouWin': '{reason} — tu gagnes',
  'live.reasonYouLose': '{reason} — tu perds',
  'live.reasonYouWinStop': '{reason} — tu gagnes.',
  'live.reasonYouLoseStop': '{reason} — tu perds.',
  'live.waitingForSomebody': 'En attente que quelqu’un ouvre ton lien.',
  'live.watching': 'Tu regardes cette partie.',
  'live.yourMove': 'À toi.',
  'live.theirMove': 'À lui.',
  'live.sendThisLink': 'Envoie ce lien à qui tu veux affronter',
  'live.linkLabel': 'Le lien vers cette partie',
  'live.copy': 'Copier',
  'live.copied': 'Copié',
  'live.pressToCopy': 'Appuie pour copier',
  'live.claimWin': 'Réclamer la victoire au temps',
  'live.offerDraw': 'Proposer la nulle',
  'live.sign': 'Signer le résultat',
  'live.signed': 'Signé',
  'live.bothSignatures':
    'Les deux signatures en font un classement que personne ne peut t’enlever. Tu peux signer maintenant ; l’autre signera quand il ouvrira le lien.',
  'live.gameTitle': '{white} contre {black} · {moves} coups',
  'live.theyWantAnother': 'Il veut une autre partie — rejoins-le',
  'live.waitingForRematch': 'En attente qu’il rejoigne ta revanche.',
  'live.playAgain': 'Rejouer contre lui',
  'live.settingUp': 'Préparation…',
  'live.noHeightYet':
    'La hauteur de bloc de cette partie n’est pas encore arrivée, et un résultat en a besoin pour se classer par rapport à tes autres parties. Attends un instant et signe à nouveau — rien n’est perdu.',
  'live.publicLink': 'Obtenir un lien que tout le monde peut vérifier',
  'live.trouble': 'Difficulté à joindre la partie. On continue d’essayer — rien n’est perdu.',
  'live.opening': 'Ouverture de la partie…',
  'live.watchOnly':
    'Tu peux regarder cette partie. Pour y jouer, ouvre-la dans Nimiq Pay afin qu’elle ait une adresse pour signer.',
  'live.alreadyTwo': 'Cette partie a déjà deux joueurs. Tu la regardes.',
  'live.expired': 'Cette partie est terminée ou expirée. Les liens durent un jour.',
  'live.leaveWarning':
    'Quitter cette partie ? Ta pendule continue de tourner, et ton adversaire pourra réclamer la victoire quand elle sera écoulée.',
  'live.stay': 'Rester',
  'live.leaveAnyway': 'Quitter quand même',

  'fail.offline':
    'Impossible de joindre la partie. Vérifie ta connexion — rien n’est perdu, et ça reprendra où tu en étais.',
  'fail.noGame': 'Cette partie est terminée ou expirée. Les liens durent un jour.',
  'fail.gameFull': 'Deux personnes y jouent déjà. Tu peux regarder.',
  'fail.notYourTurn': 'C’est à lui de jouer. Ton échiquier se mettra à jour dans un instant.',
  'fail.notAPlayer': 'Tu regardes cette partie, tu n’y joues pas.',
  'fail.notStarted': 'Personne n’a encore ouvert ton lien, donc il n’y a personne contre qui jouer.',
  'fail.gameOver': 'Cette partie est déjà terminée.',
  'fail.illegalMove': 'Ce coup n’est pas légal dans cette position. L’échiquier a été remis en place.',
  'fail.stale':
    'La partie a avancé pendant que ça circulait. Ton échiquier est à jour — réessaie.',
  'fail.notFlagged': 'Sa pendule n’est pas encore écoulée.',
  'fail.ownFlag': 'C’est ta propre pendule qui est écoulée, pas la sienne.',
  'fail.notOver': 'Une partie ne peut être signée qu’une fois terminée.',
  'fail.serverError':
    'Quelque chose a échoué de notre côté. Ta partie est en sécurité — elle est sur le serveur, et la prochaine vérification la retrouvera.',
  'fail.tooMany':
    'Ça faisait beaucoup de requêtes d’un coup. Attends quelques secondes — ta partie est en sécurité et rien n’est perdu.',
  'fail.tooLarge': 'Cette requête était trop grosse à envoyer. Celle-là, c’est notre faute, pas la tienne.',
  'fail.declined': 'Tu n’as pas signé. Rien n’a été enregistré, et tu peux signer quand tu veux.',
  'fail.cancelled': 'Annulé. Rien n’est perdu.',
  'fail.badSignature':
    'Ton portefeuille a renvoyé une signature que cette application n’a pas su lire. Signale-le, s’il te plaît — c’est notre faute, pas la tienne.',
  'fail.noStorage':
    'Ce navigateur ne laisse rien enregistrer à l’application. Tout fonctionne pour l’instant, mais ce sera perdu à la fermeture de l’onglet.',
  'fail.refused': 'Ce navigateur a refusé. Rien n’est perdu.',
  'fail.chunk': 'Une partie de l’application n’a pas pu être chargée. Recharge la page et elle reviendra.',
  'fail.network': 'Ton appareil n’a pas pu joindre le réseau. Rien n’est perdu — réessaie dans un instant.',
  'fail.notConfirmed': 'Tu n’as pas confirmé. Il ne s’est rien passé.',
  'fail.syncing': 'Nimiq Pay est encore en train de rattraper la chaîne. Laisse-lui quelques secondes.',
  'fail.somethingWith': 'Quelque chose a échoué : {detail}',
  'fail.something': 'Quelque chose a échoué. Rien n’a été signé et rien n’est perdu.',
  'fail.noWalletSign': 'La signature se fait dans l’application Nimiq Pay. Ouvre ceci là-bas.',
  'fail.noAddress': 'Le portefeuille n’a renvoyé aucune adresse.',
  'fail.phoneNetwork': 'Ton téléphone n’a pas pu joindre le réseau. Rien n’est perdu — réessaie dans un instant.',
  'fail.somethingSigning': 'Quelque chose a échoué. Rien n’a été signé.',
  'fail.timeout': '{step} — Nimiq Pay n’a pas répondu. Ouvre le portefeuille et réessaie.',

  'wallet.sharingAddress': 'Partage de ton adresse',
  'wallet.signing': 'Signature',
  'wallet.checkingSync': 'Vérification que le portefeuille est à jour',
  'wallet.readingHeight': 'Lecture de la hauteur de la chaîne',
  'wallet.identifyingDevice': 'Identification de cet appareil',

  'record.allPublished':
    'Toutes les parties ici ont été signées avec une clé publiée dans notre code — le portefeuille de démonstration, ou le bot. Les signatures se vérifient, et n’importe qui peut en produire d’autres : cela montre donc comment le chiffre est obtenu, pas à qui il appartient.',
  'record.somePublished':
    '{published} de ces {total} parties ont été signées avec une clé publiée dans notre code — le portefeuille de démonstration, ou le bot. Ces signatures se vérifient, et n’importe qui peut en produire d’autres.',
  'record.title': 'Palmarès',
  'record.noRatedGames': 'Aucune partie classée pour l’instant',
  'record.oneRatedGame': '{games} partie classée',
  'record.ratedGames': '{games} parties classées',
  'record.oneOpponent': '{count} adversaire différent',
  'record.opponents': '{count} adversaires différents',
  'record.provisional': 'Provisoire jusqu’à ce que {needed} adversaires différents aient signé. {so_far} pour l’instant.',
  'record.recompute': 'Recalculer ici',
  'record.recomputeNote':
    'Redérive chaque classement ci-dessous dans ce navigateur, à partir des seules signatures. Rien n’est demandé à notre serveur.',
  'record.checking': 'Vérification de chaque signature…',
  'record.checkedOne': '{checked} partie signée vérifiée ici, dans ce navigateur.',
  'record.checkedMany': '{checked} parties signées vérifiées ici, dans ce navigateur.',
  'record.noneRate': 'Aucune ne compte, donc le classement reste à sa valeur de départ.',
  'record.someRate': '{games} d’entre elles comptent.',
  'record.agrees': 'Ce navigateur arrive à {reached} — le même chiffre que cette page.',
  'record.disagrees':
    'Ce navigateur arrive à {reached} et cette page annonce {shown}. Si les deux divergent, c’est cette page qui a tort.',
  'record.leftOutUnsigned': '{count} pas encore signées par les deux joueurs',
  'record.leftOutInvalid': '{count} ne se vérifient pas',
  'record.leftOut': 'Laissées de côté : {detail}.',
  'record.empty': 'Aucune partie signée sur ce portefeuille pour l’instant.',
  'record.emptyNote':
    'Ce n’est ni bon ni mauvais signe — c’est un portefeuille sans palmarès. Joue une partie et signe le résultat.',
  'record.everyGame': 'Toutes les parties, dans l’ordre où elles comptent',
  'record.won': 'Gagnée',
  'record.lost': 'Perdue',
  'record.drew': 'Nulle',
  'record.casual': 'Amicale — jamais classée',
  'record.tooShort': 'Moins de {moves} coups — enregistrée, pas classée',
  'record.farmed': 'Trop de parties contre cet adversaire — cela ne bouge plus aucun des deux classements',
  'record.gameLine': '{termination} · {moves} coups · bloc {block}',
  'record.footer':
    'Chaque chiffre ici est dérivé de signatures faites par les deux joueurs. Personne ne peut le modifier — ni la personne concernée, ni nous.',

  'judge.best': 'Meilleur coup',
  'judge.bests': 'meilleurs coups',
  'judge.good': 'Bon',
  'judge.goods': 'bons coups',
  'judge.inaccuracy': 'Imprécision',
  'judge.inaccuracies': 'imprécisions',
  'judge.mistake': 'Erreur',
  'judge.mistakes': 'erreurs',
  'judge.blunder': 'Gaffe',
  'judge.blunders': 'gaffes',

  'study.title': 'Étudier une partie',
  'study.note':
    'Colle une partie en PGN — de Lichess, Chess.com, d’un tournoi, d’où tu veux — ou étudie celle que tu viens de jouer. Rien n’est signé ici et rien ne touche à ton classement.',
  'study.handedNote':
    'La partie que tu viens de jouer. Rien n’est signé ici et rien ne touche à ton classement — c’est pour la regarder.',
  'study.pasteLabel': 'Colle une partie en PGN',
  'study.open': 'L’ouvrir',
  'study.analyse': 'Analyser cette partie',
  'study.looking': 'Lecture de la partie…',
  'study.lookingProgress': 'Lecture de la partie… {done} coups sur {total}.',
  'study.wasBest': '{number} {san} — le meilleur coup ici.',
  'study.wasGood': '{number} {san} — un bon coup.',
  'study.wasWorse': '{number} {san} — {label}. {better} était meilleur, de {lost} points de chances de gain.',
  'study.acpl': '{acpl} centipions perdus par coup',
  'study.whiteAhead': 'Les Blancs sont devant — {percent} pour cent',
  'study.blackAhead': 'Les Noirs sont devant — {percent} pour cent',
  'study.nothingToComplain': 'rien à redire',
  'study.caveat':
    'Analysée par le moteur maison de cette application, sur ton appareil — niveau club, pas Stockfish. Il trouvera les gaffes d’une partie ordinaire et ne contredira pas un grand maître.',
  'study.reviewed': 'La partie est analysée. Parcours-la pour voir le jugement de chaque coup.',
  'study.analysisFailed': 'L’analyse s’est arrêtée : {detail}. C’est notre faute — signale-le, s’il te plaît.',
  'study.playersVs': '{white} contre {black}',
  'study.animported': 'Une partie importée',
  'study.heading': '{players} · {moves} coups',
  'study.loaded': '{plies} coups chargés. Parcours-les avec les flèches.',

  'cert.title': 'Une partie signée',
  'cert.fetching': 'Récupération de la partie…',
  'cert.stillPlaying': 'Cette partie est encore en cours. Le certificat apparaît quand elle se termine.',
  'cert.unreconstructable': 'Cette partie ne peut pas être reconstituée, donc rien ici n’est vérifiable.',
  'cert.onlyOne': 'Un seul joueur a signé pour l’instant. Cela devient une trace quand les deux l’ont fait.',
  'cert.verified':
    'Les deux joueurs ont signé ce résultat, et ce navigateur vient de vérifier les deux signatures.',
  'cert.bad': 'Ces signatures ne tiennent pas. Ne crois pas ce résultat.',
  'cert.nothingAsked':
    'Rien n’a été demandé à notre serveur pour arriver à cette conclusion, hormis la partie elle-même — les signatures ont été vérifiées ici, sur ton appareil, contre le texte exact que les deux joueurs ont signé.',
  'cert.checkFailed': 'La vérification a échoué : {reason}.',
  'cert.unknown': 'inconnu',
  'cert.winnersRecord': 'Voir le palmarès du gagnant',
  'cert.playYourself': 'Joue une partie toi-même',
  'cert.signed': 'signée',
  'cert.notSignedYet': 'pas encore signée',

  'certificate.abandoned': 'Abandonnée',
  'certificate.cannotDraw': 'Ce navigateur ne peut pas dessiner de certificat.',
  'certificate.noPicture': 'L’image n’a pas pu être créée.',
  'certificate.whiteWins': 'Les Blancs gagnent',
  'certificate.blackWins': 'Les Noirs gagnent',
  'certificate.drawn': 'Partie nulle',
  'certificate.rated': 'classée',
  'certificate.casual': 'amicale',
  'certificate.summary': '{reason} · {moves} coups · {kind}',
  'certificate.bothSigned': 'Les deux joueurs ont signé ce résultat',
  'certificate.evidence':
    'Bloc Nimiq {block} · partie {game}… · tout le monde peut le vérifier sur {where}',
  'certificate.signatureOf': 'Signature de {side}',
  'certificate.tagline': 'Un classement que personne n’a délivré et que personne ne peut révoquer.',

  'share.asPicture': 'Partager en image',
  'share.asPgn': 'Enregistrer en PGN',
  'share.sent': 'Envoyé.',
  'share.savedPicture': 'Enregistré en image.',
  'share.savedPgn': 'Enregistré en PGN, que tous les programmes d’échecs lisent.',
  'share.notOnDevice': 'Cette partie n’est plus sur cet appareil.',
  'share.didNotWork': 'Ça n’a pas marché sur cet appareil. La partie est en sécurité dans tous les cas.',

  'sign.notOver': 'Cette partie n’est pas encore terminée.',
  'sign.syncing':
    'Nimiq Pay est encore en train de rattraper la chaîne. Laisse-lui quelques secondes et signe à nouveau.',
  'sign.noHeight':
    'Nimiq Pay n’a pas pu lire la hauteur de la chaîne à l’instant, et une partie en a besoin pour être classée. Réessaie dans un moment.',
  'sign.notYourGame': 'Ce portefeuille n’a pas joué cette partie, il n’y a donc rien à signer ici pour lui.',

  'api.offline': 'Impossible de joindre la partie. Vérifie ta connexion.',
  'api.something': 'Quelque chose a échoué.',
  'api.badShape':
    'Le serveur a envoyé quelque chose que cette application n’a pas su lire. C’est notre faute, pas la tienne — ta partie est en sécurité sur le serveur.',
  'poolApi.offline': 'Impossible de joindre la cagnotte.',
  'poolApi.refused': 'Cette réclamation n’a pas pu aboutir.',
  'poolApi.alreadyClaimed': 'Tu as déjà réclamé aujourd’hui. Le problème change à minuit, et ceci aussi.',
  'poolApi.deviceClaimed':
    'Cet appareil a déjà réclamé aujourd’hui — un par appareil, et c’est ce qui empêche un script de vider la cagnotte.',
  'poolApi.notFunded':
    'La cagnotte n’est pas alimentée en ce moment, il n’y a donc rien à réclamer. Résoudre compte quand même pour ta série.',
  'poolApi.needsNimiqPay':
    'Réclamer demande Nimiq Pay, qui est ce qui dit à la cagnotte que deux réclamations viennent de deux personnes différentes.',
  'poolApi.unreachable':
    'Impossible de joindre la cagnotte. Ta solution est en sécurité — réessaie de réclamer dans un instant.',

  'send.needsNimiqPay': 'L’envoi de NIM se fait dans l’application Nimiq Pay. Ouvre ceci là-bas.',
  'send.memoTooLong': 'Ce message est trop long pour une transaction Nimiq. Celui-là, c’est notre faute.',
  'send.badAmount': 'Ce n’est pas un montant qui peut être envoyé.',
  'send.waiting': 'En attente de ton portefeuille',
  'send.declined': 'Rien n’a été envoyé. Tes NIM sont là où ils étaient.',
  'send.failed': 'Cela n’a pas pu être envoyé. Rien n’est sorti de ton portefeuille.',
  'send.tip': 'Envoie-lui {amount} NIM',
  'send.tipTitle': 'Belle partie ?',
  'send.tipNote':
    'Envoie-lui des NIM directement depuis ton portefeuille. Ils ne passent pas par nous, et la transaction dit de quelle partie il s’agit.',
  'send.tipSent': 'Envoyé. {amount} NIM sont passés de ton portefeuille au sien.',
  'send.poolTitle': 'Remets-en un peu',
  'send.poolNote':
    'La cagnotte paie un inconnu pour avoir résolu le problème du jour. N’importe qui peut y ajouter, et chaque versement qu’elle fait est sur la chaîne avec le problème inscrit dedans.',
  'send.poolAdd': 'Ajouter {amount} NIM à la cagnotte',
  'send.poolSent': 'Envoyé. {amount} NIM sont dans la cagnotte pour le prochain qui résoudra.',
  'send.sending': 'En attente de ton portefeuille…',

  'app.broke': 'Quelque chose s’est cassé',

  /* ---------------------------------------------------------------- the portable record */
  'record.take': 'Emporte ton palmar\u00e8s',
  'record.takeNote':
    'Un fichier avec chaque partie et chaque s\u00e9rie de probl\u00e8mes sign\u00e9es sur cet appareil. N\u2019importe qui peut le v\u00e9rifier sans ce site et sans rien nous demander.',
  'record.takeButton': 'Enregistrer mon palmar\u00e8s',
  'record.takeEmpty': 'Rien n\u2019est encore sign\u00e9 sur cet appareil.',
  'record.recordSent': 'Envoy\u00e9 \u2014 {games} parties et {runs} s\u00e9ries de probl\u00e8mes.',
  'record.recordSaved': 'Enregistr\u00e9 \u2014 {games} parties et {runs} s\u00e9ries de probl\u00e8mes.',
  'record.recordSkipped': '{count} laiss\u00e9es de c\u00f4t\u00e9 : non sign\u00e9es des deux c\u00f4t\u00e9s, ou venant de l\u2019autre r\u00e9seau.',

  /* ---------------------------------------------------------------- the verify screen */
  'verify.title': 'V\u00e9rifier un palmar\u00e8s',
  'verify.intro':
    'Quelqu\u2019un vous a envoy\u00e9 un palmar\u00e8s Scoresheet ? Ouvrez-le ici. Votre navigateur v\u00e9rifie chaque signature et recalcule le classement lui-m\u00eame. Rien n\u2019est envoy\u00e9, et cette page n\u2019a pas besoin de notre serveur.',
  'verify.choose': 'Choisir un fichier',
  'verify.checking': 'V\u00e9rification de chaque signature\u2026',
  'verify.unreadable': 'Ce fichier n\u2019a pas pu \u00eatre lu.',
  'verify.notARecord': 'Ce n\u2019est pas un palmar\u00e8s Scoresheet.',
  'verify.oneGame': '1 partie v\u00e9rifi\u00e9e, et {runs} s\u00e9ries de probl\u00e8mes.',
  'verify.manyGames': '{games} parties v\u00e9rifi\u00e9es, et {runs} s\u00e9ries de probl\u00e8mes.',
  'verify.rating': 'Classement {rating}, sur {games} parties class\u00e9es contre {opponents} personnes diff\u00e9rentes.',
  'verify.noneRate': 'Aucune de ces parties n\u2019est class\u00e9e, il n\u2019y a donc pas de classement \u00e0 v\u00e9rifier.',
  'verify.provisional': 'Provisoire : un classement se stabilise apr\u00e8s dix adversaires diff\u00e9rents.',
  'verify.puzzleRating': 'Classement aux probl\u00e8mes {rating}.',
  'verify.findings': 'Ce qui ne colle pas',
  'verify.badSignature': 'Partie {id} : la signature {side} ne correspond pas.',
  'verify.notTheirs': 'Une partie appartenant \u00e0 quelqu\u2019un d\u2019autre a \u00e9t\u00e9 \u00e9cart\u00e9e.',
  'verify.wrongChain': 'Une partie de l\u2019autre r\u00e9seau a \u00e9t\u00e9 \u00e9cart\u00e9e.',
  'verify.malformed': 'Une entr\u00e9e n\u2019a pas pu \u00eatre lue : {detail}',
  'verify.gameRootMismatch': 'Les parties ne donnent pas l\u2019empreinte que ce palmar\u00e8s annonce. Quelque chose a \u00e9t\u00e9 ajout\u00e9 ou retir\u00e9 apr\u00e8s coup.',
  'verify.runRootMismatch': 'Les s\u00e9ries de probl\u00e8mes ne donnent pas l\u2019empreinte que ce palmar\u00e8s annonce.',
  'verify.anchorBefore': 'Ce palmar\u00e8s pr\u00e9tend avoir \u00e9t\u00e9 ancr\u00e9 sur la cha\u00eene avant l\u2019une de ses propres parties.',
  'verify.anchored': 'Ancr\u00e9 sur la cha\u00eene Nimiq, apr\u00e8s la derni\u00e8re partie qu\u2019il contient.',
  'verify.caveat':
    'Cela prouve que ces parties ont eu lieu et n\u2019ont pas \u00e9t\u00e9 modifi\u00e9es. Cela ne prouve pas que la liste est compl\u00e8te \u2014 on peut omettre une d\u00e9faite d\u2019un palmar\u00e8s que l\u2019on publie soi-m\u00eame.',

  'study.tryAgain': 'Essayez vous-m\u00eame',
  'study.tryGiveUp': 'Montrez-moi',
  'study.tryPrompt': '\u00c0 vous de jouer. Trouvez mieux que ce que vous avez jou\u00e9.',
  'study.tryThinking': 'Analyse en cours\u2026',
  'study.tryFound': '{san} \u2014 c\u2019est \u00e7a. C\u2019est ce que voulait le moteur.',
  'study.tryBetter': '{san} vaut mieux que votre coup, sans \u00eatre le meilleur. Il co\u00fbte {lost} points \u00e0 la place.',
  'study.tryNo': '{san} co\u00fbte {lost} points \u2014 pas mieux que votre coup. Essayez autre chose.',
  'study.tryUnknown': 'Le moteur n\u2019a pas r\u00e9pondu \u00e0 temps ; ce coup reste non jug\u00e9.',

  'study.trainThis': 'S’entraîner là-dessus',
  'study.trainChecking': 'Vérification que cela ferait un problème honnête…',
  'study.trainAdded': 'Ajouté à votre entraînement. Vous reverrez cette position.',
  'study.trainAlready': 'Celle-ci est déjà dans votre entraînement.',
  'study.trainNotUnique': 'Non ajouté : il y a ici plus d’un bon coup, ce ne serait pas un problème honnête.',
  'study.trainNotSuitable': 'Non ajouté : le meilleur coup ici n’est pas ce qu’un problème peut demander.',
  'study.trainNotSound': 'Non ajouté : un examen plus long n’a pas confirmé le premier.',
  'study.trainUnknown': 'Le moteur n’a pas répondu à temps ; rien n’a été ajouté.',
  'puzzles.mine': 'Vos propres erreurs',
  'puzzles.mineDetail': '{count} en attente. Des positions que vous avez ratées, les pires d’abord.',
  'puzzles.mineDone': 'C’est tout. Vous avez repris chaque erreur que vous aviez gardée.',

  /* ---------------------------------------------------------------- tournaments */
  'lobby.tourneyTitle': 'Organiser un tournoi',
  'lobby.tourneyNote': 'Toutes rondes, ou système suisse au-delà de huit. Vous recevez un lien à envoyer aux joueurs.',
  'lobby.seats': 'Joueurs',
  'lobby.seats4': 'Quatre',
  'lobby.seats4Detail': 'Six parties, une ronde chacune',
  'lobby.seats6': 'Six',
  'lobby.seats6Detail': 'Quinze parties',
  'lobby.seats8': 'Huit',
  'lobby.seats8Detail': 'Toutes rondes',
  'lobby.seats12': 'Douze',
  'lobby.seats12Detail': 'Suisse, cinq rondes',
  'lobby.hold': 'Organiser un tournoi',
  'lobby.tourneyName': 'Tournoi',
  'tourney.title': 'Tournoi',
  'tourney.loading': 'Chargement du tournoi\u2026',
  'tourney.notFound': 'Aucun tournoi ne correspond \u00e0 ce lien.',
  'tourney.unavailable': 'Ce tournoi n\u2019a pas pu \u00eatre charg\u00e9 pour le moment.',
  'tourney.open': 'Ouvert \u2014 {entrants} places sur {seats} prises.',
  'tourney.running': 'En cours \u2014 {entrants} joueurs.',
  'tourney.finished': 'Termin\u00e9 \u2014 {entrants} joueurs.',
  'tourney.agrees': 'Ce navigateur a recalcul\u00e9 le tableau lui-m\u00eame, \u00e0 partir des parties, et retrouve le m\u00eame ordre.',
  'tourney.disagrees': 'Ce navigateur obtient un autre tableau \u00e0 partir de ces parties. Quelque chose ne colle pas.',
  'tourney.standings': 'Classement',
  'tourney.games': 'Parties',
  'tourney.round': 'Ronde {round}',
  'tourney.toPlay': '\u00e0 jouer',
  'tourney.prize': '{nim} NIM',
  'tourney.caveat': 'Chaque partie ci-dessus a été vérifiée dans ce navigateur, face à ses deux signatures. Le classement découle de ces parties, et vous venez de le voir se calculer.',
  'tourney.agreesSigned': 'Ce navigateur a vérifié lui-même les {games} parties signées et obtenu le même tableau, sans rien nous demander.',
  'tourney.dropped': '{games} parties soumises n’ont pas pu être vérifiées et ont été écartées du tableau.',
  'tourney.caveatUnchecked': 'Le classement découle de ces résultats, et vous venez de le vérifier vous-même. Savoir si ce sont bien les résultats est une autre question, à laquelle chaque partie répond sur son propre certificat.',
  'tourney.join': 'Rejoindre ce tournoi',
  'tourney.joinFailed': 'Ça n’est pas passé. Les places sont peut-être prises.',
  'tourney.yours': 'Vos parties',
  'tourney.playThem': 'pas encore jouée',
  'tourney.report': 'Envoyer la partie',
  'tourney.reportFailed': 'Cette partie n’a pas été acceptée. Elle doit être signée par vous deux.',
  'tourney.back': 'Retour',
};
