/**
 * Português.
 *
 * Written against `en.ts`, which owns the key set — `i18n.test.ts` fails if a key here is missing or
 * invented. Chess vocabulary is the standard Portuguese set (*xeque-mate*, *rei afogado*, *empate*,
 * *brancas*, *pretas*, *bispo*, *cavalo*, *torre*, *dama*), and the register matches the English:
 * plain, about the game rather than the software, and never blaming the person reading it.
 *
 * Addressed as **você** and written to read naturally in both Brazil and Portugal.
 */

import type { en } from './en.ts';

export const pt: Record<keyof typeof en, string> = {
  'nav.sections': 'Secções',
  'nav.play': 'Jogar',
  'nav.train': 'Treinar',
  'nav.you': 'Você',
  'nav.noRecord':
    'O seu histórico aparece aqui assim que assinar uma partida. Termine uma e assine o resultado — é um toque.',

  'moves.label': 'Lances',
  'moves.empty': 'Os lances aparecem aqui enquanto você joga.',
  'moves.viewingEarlier': 'Está a ver uma posição anterior',
  'moves.toStart': 'Ir para o início',
  'moves.back': 'Lance anterior',
  'moves.forward': 'Lance seguinte',
  'moves.toLive': 'Voltar à posição atual',
  'moves.namedAfter': '{eco} · nomeada ao fim de {plies} lances',
  'moves.namedAfterOne': '{eco} · nomeada ao fim de {plies} lance',

  'board.label': 'Tabuleiro de xadrez',
  'board.square': '{square}, {piece}',
  'board.empty': 'vazia',
  'board.promote': 'Escolha uma peça para a promoção',

  'piece.pawn': 'peão',
  'piece.knight': 'cavalo',
  'piece.bishop': 'bispo',
  'piece.rook': 'torre',
  'piece.queen': 'dama',
  'piece.king': 'rei',
  'piece.piece': 'peça',

  'lobby.title': 'Jogar com um amigo',
  'lobby.note':
    'Recebe um link. Quem o abrir fica com o outro lado — não precisa de conta nem de carteira para jogar.',
  'lobby.time': 'Tempo',
  'lobby.youPlay': 'Você joga de',
  'lobby.make': 'Criar o link',
  'lobby.making': 'A criar…',
  'lobby.study': 'Ou estude uma partida a partir de um PGN',
  'lobby.needsWallet':
    'Uma partida contra outra pessoa precisa de uma carteira para assinar o resultado. Abra isto no Nimiq Pay, ou jogue contra o bot — isso não precisa de nada.',

  'time.bullet': 'Bullet',
  'time.bulletDetail': '1 minuto para cada',
  'time.blitz': 'Blitz',
  'time.blitzDetail': '3 minutos, 2 segundos por lance',
  'time.rapid': 'Rápidas',
  'time.rapidDetail': '10 minutos, 5 segundos por lance',
  'time.unlimited': 'Sem relógio',
  'time.unlimitedDetail': 'Demore o tempo que quiser',

  'colour.random': 'Ao acaso',
  'colour.randomDetail': 'O habitual',
  'colour.white': 'Brancas',
  'colour.whiteDetail': 'Você joga primeiro',
  'colour.black': 'Pretas',
  'colour.blackDetail': 'O outro joga primeiro',

  'today.title': 'Hoje',
  'today.daily': 'Resolver o problema do dia',
  'today.game': 'Jogar uma partida',
  'today.win': 'Ganhar uma',
  'today.done': 'feito',
  'today.notYet': 'ainda não',

  'puzzles.title': 'Problemas',
  'puzzles.rating': 'rating de problemas',
  'puzzles.dayInARow': 'dia seguido',
  'puzzles.daysInARow': 'dias seguidos',
  'puzzles.bestStreak': 'melhor sequência',
  'puzzles.bestStorm': 'melhor tempestade',
  'puzzles.note':
    'Estes números vivem neste dispositivo e ninguém os assina. O seu rating na página de histórico é o contrário: duas assinaturas, e ninguém lho pode tirar.',
  'puzzles.daily': 'Problema do dia',
  'puzzles.dailyDone': 'O problema de hoje — feito',
  'puzzles.dailyDetail': 'O mesmo problema que toda a gente recebeu hoje.',
  'puzzles.train': 'Treinar',
  'puzzles.trainDetail': 'Sem fim, e encontra o seu nível pelo caminho.',
  'puzzles.storm': 'Tempestade',
  'puzzles.stormDetail': 'Três minutos. Tantos quantos conseguir.',
  'puzzles.streak': 'Sequência',
  'puzzles.streakDetail': 'Sem relógio. Acaba no primeiro erro.',
  'puzzles.oneIdea': 'Ou treine uma só ideia',
  'coords.title': 'Coordenadas',
  'coords.note':
    'Saber onde está uma casa sem contar é a competência que todos os livros de xadrez dão por sabida. Trinta segundos, tantas quantas conseguir.',
  'coords.menuDetail': 'Trinta segundos para encontrar o máximo de casas que conseguir.',
  'coords.mode': 'Modo',
  'coords.findSquare': 'Encontrar a casa',
  'coords.nameSquare': 'Nomear a casa',
  'coords.playAs': 'Você joga de',
  'coords.showPieces': 'Mostrar as peças',
  'coords.start': 'Começar',
  'coords.again': 'Outra vez',
  'coords.change': 'Mudar as definições',
  'coords.findThis': '{square}',
  'coords.nameThis': 'Nomeie a casa iluminada',
  'coords.thisSquare': 'a casa a nomear',
  'coords.score': '{correct} certas · faltam {left} segundos',
  'coords.youScored': 'Fez {score}.',
  'coords.average': 'De {side}: {average} em média, recorde {best}',
  'coords.noAverage': 'De {side}: ainda nada',

  'puzzles.credit': 'Problemas da base de dados aberta do Lichess, cedida ao domínio público.',

  'theme.mateIn1': 'Mate em 1',
  'theme.mateIn2': 'Mate em 2',
  'theme.backRankMate': 'Última fila',
  'theme.fork': 'Garfos',
  'theme.pin': 'Cravadas',
  'theme.skewer': 'Espetos',
  'theme.discoveredAttack': 'Ataques descobertos',
  'theme.deflection': 'Desvio',
  'theme.sacrifice': 'Sacrifícios',
  'theme.hangingPiece': 'Peças penduradas',
  'theme.endgame': 'Finais',
  'theme.promotion': 'Promoção',

  'puzzles.stormScore': '{solved} resolvidos · faltam {left} · recorde {best}',
  'puzzles.streakScore': '{solved} seguidos · recorde {best}',
  'puzzles.trainScore': 'O seu rating de problemas é {rating} · só neste dispositivo',
  'puzzles.oneDayRun': '{days} dia seguido',
  'puzzles.dayRun': '{days} dias seguidos',
  'puzzles.startARun': 'Resolva-o para começar uma sequência de dias',
  'puzzles.noPuzzle': 'Não foi possível carregar nenhum problema. A culpa é nossa, não sua.',
  'puzzles.themesAndRating': '{themes} · rating {rating}',
  'puzzles.ratingOnly': 'Rating {rating}',
  'puzzles.watchTheirMove': 'Veja o lance dele…',
  'puzzles.whiteToPlay': 'Jogam as brancas. Encontre o melhor lance.',
  'puzzles.blackToPlay': 'Jogam as pretas. Encontre o melhor lance.',
  'puzzles.rightKeepGoing': 'Certo. Continue.',
  'puzzles.solved': 'Resolvido.',
  'puzzles.solvedToday': 'Resolvido. O dia de hoje está feito.',
  'puzzles.trainOnMore': 'Treinar com mais problemas',
  'puzzles.runEnds': 'Esse não. A sequência acaba em {solved}.',
  'puzzles.anotherRun': 'Começar outra sequência',
  'puzzles.stormPenalty': 'Esse não — {seconds} segundos.',
  'puzzles.tryAgain': 'Esse não. Tente outra vez, ou veja a solução.',
  'puzzles.skip': 'Saltar este',
  'puzzles.showAnswer': 'Ver a solução',
  'puzzles.theMoveWas': 'O lance era {move}.',
  'puzzles.thatIsTheLine': 'É essa a linha.',
  'puzzles.timeUp': 'Acabou o tempo. {solved} resolvidos.',
  'puzzles.runItAgain': 'Outra vez',

  'pool.allClaimed':
    'Hoje já foram reclamadas todas as recompensas. O fundo vem dos rendimentos de staking, por isso volta a encher-se amanhã em vez de se esgotar.',
  'pool.notFunded': 'O fundo de problemas ainda não tem dinheiro. Resolver continua a contar para a sua sequência.',
  'pool.thereIs': 'Há {amount} no fundo para o problema de hoje.',
  'pool.claim': 'Reclamar {amount}',
  'pool.claiming': 'A reclamar…',
  'pool.needsWallet':
    'A recompensa é paga em NIM, por isso precisa de uma carteira onde chegar. Abra isto no Nimiq Pay e reclamá-la é um toque.',
  'pool.deviceReason': 'Para o fundo distinguir uma reclamação da outra',
  'pool.sent': 'Foram enviados {amount} para a sua carteira. A transação diz de que problema se trata.',
  'pool.recorded':
    '{amount} são seus e a reclamação está registada, mas a transação ainda não saiu. Será enviada — não se perde nada.',

  'common.backToBoard': 'Voltar ao tabuleiro',

  'settings.title': 'Definições',
  'settings.done': 'Pronto',
  'settings.opponent': 'Adversário',
  'settings.opponentHelp': 'Mudar isto começa uma partida nova.',
  'settings.board': 'O tabuleiro',
  'settings.boardColours': 'Cores do tabuleiro',
  'settings.wood': 'Madeira',
  'settings.slate': 'Ardósia',
  'settings.sea': 'Mar',
  'settings.moveDots': 'Pontos de lance',
  'settings.moveDotsHelp': 'Mostra para onde pode ir a peça que levantar.',
  'settings.coordinates': 'Coordenadas',
  'settings.coordinatesHelp': 'Letras de coluna e números de fila na margem.',
  'settings.autoQueen': 'Promover sempre a dama',
  'settings.autoQueenHelp': 'Desligue isto para escolher torre, bispo ou cavalo.',
  'settings.zen': 'Zen',
  'settings.zenHelp': 'Só o tabuleiro. Mais nada no ecrã.',
  'settings.blindfold': 'Às cegas',
  'settings.blindfoldHelp':
    'Esconde as peças e joga-se pela lista de lances. É tão difícil como parece.',
  'settings.feedback': 'Resposta',
  'settings.sound': 'Som',
  'settings.soundHelp': 'Lance, captura, xeque e fim de partida.',
  'settings.haptics': 'Vibração',
  'settings.hapticsHelp': 'Uma vibração curta nos telemóveis que a suportam.',
  'settings.language': 'Idioma',
  'settings.languageHelp': 'Segue o Nimiq Pay a não ser que escolha um.',
  'settings.languageAuto': 'Automático',

  'level.looksGood': 'Joga a primeira coisa que lhe parece bem',
  'level.oneAhead': 'Pensa um ou dois lances à frente',
  'level.simpleTactics': 'Vê quase todas as táticas simples',
  'level.punishes': 'Castiga uma peça solta',

  'result.checkmate': 'Xeque-mate',
  'result.stalemate': 'Rei afogado — empate',
  'result.insufficient': 'Material insuficiente para dar mate — empate',
  'result.fiftyMove': 'Cinquenta lances sem captura nem lance de peão — empate',
  'result.repetition': 'A mesma posição cinco vezes — empate',
  'result.gameOver': 'Fim da partida',
  'result.whiteWins': ' — ganham as brancas',
  'result.blackWins': ' — ganham as pretas',
  'result.check': ' — xeque',

  'record.puzzleRating': 'Pontuação de problemas',
  'puzzles.signing': 'Assinando esta série…',
  'puzzles.seeRecord': 'Ver seu histórico',
  'puzzles.makeCount': 'Que minhas séries contem',
  'puzzles.loading': 'Carregando problemas…',
  'puzzles.dailyDoneNote': 'O problema de hoje já foi resolvido. Volte amanhã.',
  'puzzles.trainMore': 'Treinar com mais problemas',
  'puzzles.backToBoard': 'Voltar ao tabuleiro',
  'game.claim': 'Uma pontuação de xadrez que ninguém pode tirar de você. Os dois jogadores assinam o resultado — não nós.',
  'game.resign': 'Desistir',
  'game.resignAgain': 'Toque outra vez para desistir',
  'game.takeback': 'Voltar atrás',
  'game.backToStart': 'De volta ao início. É a sua vez.',
  'game.takenBack': 'Lance desfeito. É a sua vez.',
  'game.flip': 'Virar o tabuleiro',
  'game.newGame': 'Partida nova',
  'game.playFriend': 'Jogar com um amigo',
  'game.leaveZen': 'Sair do modo zen, ou mudar as definições',
  'game.resignedBlackWins': 'Você desistiu — ganham as pretas',
  'game.resignedWhiteWins': 'Você desistiu — ganham as brancas',
  'game.rematch': 'A desforra',
  'game.review': 'Ver onde correu mal',
  'game.youVs': 'Você contra {bot} · {moves} lances',
  'game.seeRecord': 'Ver o seu histórico',
  'game.yourMoveAsWhite': 'É a sua vez. Joga de brancas, contra {bot}.',
  'game.botIsWhite': '{bot} joga de brancas. É a vez dele.',
  'game.youFlagged': 'O seu tempo acabou.',
  'game.theyFlagged': 'O tempo dele acabou — você ganha.',
  'game.clock': 'Relógio',
  'game.clockHelp': 'Mudar isto começa uma partida nova.',
  'game.newGameAgainst': 'Partida nova contra {bot}.',

  'sign.button': 'Assine o resultado para que conte',
  'sign.waiting': 'À espera da sua carteira…',
  'sign.whatWasSigned': 'O que foi assinado',
  'sign.done': 'Assinado. Este resultado é seu, e qualquer pessoa o pode verificar sem nós.',
  'sign.demoDone':
    'Assinado com a carteira de demonstração. A assinatura é real e verifica-se — mas a chave está publicada no nosso código, por isso prova o mecanismo, não que seja você.',
  'sign.needsNimiqPay':
    'A assinatura acontece na aplicação Nimiq Pay. Abra isto por lá e o resultado passa a ser seu.',
  'sign.invitation':
    'Assine o resultado e ele passa a ser seu — um registo que ninguém pode revogar, verificável sem nós.',

  'live.checkmate': 'Xeque-mate',
  'live.resignation': 'Desistência',
  'live.timeout': 'Tempo',
  'live.stalemate': 'Rei afogado',
  'live.insufficient': 'Material insuficiente para dar mate',
  'live.repetition': 'Tripla repetição',
  'live.fiftyMove': 'Regra dos cinquenta lances',
  'live.agreement': 'Empate acordado',
  'live.reasonDraw': '{reason} — empate',
  'live.reasonYouWin': '{reason} — você ganha',
  'live.reasonYouLose': '{reason} — você perde',
  'live.reasonYouWinStop': '{reason} — você ganha.',
  'live.reasonYouLoseStop': '{reason} — você perde.',
  'live.waitingForSomebody': 'À espera de que alguém abra o seu link.',
  'live.watching': 'Está a assistir a esta partida.',
  'live.yourMove': 'É a sua vez.',
  'live.theirMove': 'É a vez dele.',
  'live.sendThisLink': 'Envie este link a quem quiser desafiar',
  'live.linkLabel': 'O link para esta partida',
  'live.copy': 'Copiar',
  'live.copied': 'Copiado',
  'live.pressToCopy': 'Prima para copiar',
  'live.claimWin': 'Reclamar a vitória por tempo',
  'live.offerDraw': 'Propor empate',
  'live.sign': 'Assinar o resultado',
  'live.signed': 'Assinado',
  'live.bothSignatures':
    'As duas assinaturas fazem disto um rating que ninguém lhe pode tirar. Pode assinar agora; o outro assina quando abrir o link.',
  'live.gameTitle': '{white} contra {black} · {moves} lances',
  'live.theyWantAnother': 'Ele quer outra partida — junte-se',
  'live.waitingForRematch': 'À espera de que ele entre na sua desforra.',
  'live.playAgain': 'Jogar outra vez',
  'live.settingUp': 'A preparar…',
  'live.noHeightYet':
    'A altura de bloco desta partida ainda não chegou, e um resultado precisa de uma para ser ordenado em relação às suas outras partidas. Espere um momento e assine outra vez — não se perde nada.',
  'live.publicLink': 'Obter um link que qualquer pessoa pode verificar',
  'live.trouble': 'Dificuldade em chegar à partida. Continuamos a tentar — não se perde nada.',
  'live.opening': 'A abrir a partida…',
  'live.watchOnly':
    'Pode assistir a esta partida. Para jogar, abra-a no Nimiq Pay para que tenha um endereço com que assinar.',
  'live.alreadyTwo': 'Esta partida já tem dois jogadores. Está a assistir.',
  'live.expired': 'Essa partida terminou ou expirou. Os links duram um dia.',
  'live.leaveWarning':
    'Sair desta partida? O seu relógio continua a correr, e o seu adversário pode reclamar a vitória quando ele acabar.',
  'live.stay': 'Ficar',
  'live.leaveAnyway': 'Sair na mesma',

  'fail.offline':
    'Não foi possível chegar à partida. Verifique a ligação — não se perde nada, e continua onde ficou.',
  'fail.noGame': 'Essa partida terminou ou expirou. Os links duram um dia.',
  'fail.gameFull': 'Já há duas pessoas a jogar esta. Pode assistir.',
  'fail.notYourTurn': 'É a vez dele. O seu tabuleiro vai atualizar-se daqui a pouco.',
  'fail.notAPlayer': 'Está a assistir a esta partida, não a jogá-la.',
  'fail.notStarted': 'Ainda ninguém abriu o seu link, por isso não há contra quem jogar.',
  'fail.gameOver': 'Essa partida já terminou.',
  'fail.illegalMove': 'Esse lance não é legal nesta posição. O tabuleiro foi reposto.',
  'fail.stale':
    'A partida avançou enquanto isso ia a caminho. O seu tabuleiro já está atualizado — tente outra vez.',
  'fail.notFlagged': 'O relógio dele ainda não acabou.',
  'fail.ownFlag': 'O relógio que acabou é o seu, não o dele.',
  'fail.notOver': 'Uma partida só pode ser assinada depois de terminar.',
  'fail.serverError':
    'Alguma coisa correu mal do nosso lado. A sua partida está segura — está no servidor, e a próxima verificação encontra-a.',
  'fail.tooMany':
    'Foram muitos pedidos de uma vez. Espere alguns segundos — a sua partida está segura e não se perdeu nada.',
  'fail.tooLarge': 'Esse pedido era grande demais para enviar. Este é problema nosso, não seu.',
  'fail.declined': 'Não assinou. Não foi registado nada, e pode assinar quando quiser.',
  'fail.cancelled': 'Cancelado. Não se perdeu nada.',
  'fail.badSignature':
    'A sua carteira devolveu uma assinatura que esta aplicação não conseguiu ler. Avise-nos, por favor — a culpa é nossa, não sua.',
  'fail.noStorage':
    'Este navegador não deixa a aplicação guardar nada. Por agora tudo funciona, mas perde-se quando fechar o separador.',
  'fail.refused': 'Este navegador recusou. Não se perdeu nada.',
  'fail.chunk': 'Uma parte da aplicação não conseguiu carregar. Recarregue a página e ela volta.',
  'fail.network': 'O seu dispositivo não chegou à rede. Não se perdeu nada — tente daqui a pouco.',
  'fail.notConfirmed': 'Não confirmou. Não aconteceu nada.',
  'fail.syncing': 'O Nimiq Pay ainda está a pôr-se em dia com a cadeia. Dê-lhe alguns segundos.',
  'fail.somethingWith': 'Alguma coisa correu mal: {detail}',
  'fail.something': 'Alguma coisa correu mal. Não foi assinado nada e não se perdeu nada.',
  'fail.noWalletSign': 'A assinatura acontece na aplicação Nimiq Pay. Abra isto por lá.',
  'fail.noAddress': 'A carteira não devolveu nenhum endereço.',
  'fail.phoneNetwork': 'O seu telemóvel não chegou à rede. Não se perdeu nada — tente daqui a pouco.',
  'fail.somethingSigning': 'Alguma coisa correu mal. Não foi assinado nada.',
  'fail.timeout': '{step} — o Nimiq Pay não respondeu. Abra a carteira e tente outra vez.',

  'wallet.sharingAddress': 'A partilhar o seu endereço',
  'wallet.signing': 'A assinar',
  'wallet.checkingSync': 'A verificar se a carteira está em dia',
  'wallet.readingHeight': 'A ler a altura da cadeia',
  'wallet.identifyingDevice': 'A identificar este dispositivo',

  'record.allPublished':
    'Todas as partidas aqui foram assinadas com uma chave publicada no nosso código — a carteira de demonstração, ou o bot. As assinaturas verificam-se, e qualquer pessoa pode criar mais, por isso isto mostra como se chega ao número e não de quem ele é.',
  'record.somePublished':
    '{published} destas {total} partidas foram assinadas com uma chave publicada no nosso código — a carteira de demonstração, ou o bot. Essas assinaturas verificam-se, e qualquer pessoa pode criar mais.',
  'record.title': 'Histórico',
  'record.noRatedGames': 'Ainda não há partidas a contar para o rating',
  'record.oneRatedGame': '{games} partida a contar',
  'record.ratedGames': '{games} partidas a contar',
  'record.oneOpponent': '{count} adversário diferente',
  'record.opponents': '{count} adversários diferentes',
  'record.provisional': 'Provisório até {needed} adversários diferentes terem assinado. Vai em {so_far}.',
  'record.recompute': 'Recalcular aqui',
  'record.recomputeNote':
    'Volta a derivar cada rating abaixo neste navegador, só a partir das assinaturas. Nada é pedido ao nosso servidor.',
  'record.checking': 'A verificar cada assinatura…',
  'record.checkedOne': 'Verificada {checked} partida assinada aqui, neste navegador.',
  'record.checkedMany': 'Verificadas {checked} partidas assinadas aqui, neste navegador.',
  'record.noneRate': 'Nenhuma conta, por isso o rating fica no valor inicial.',
  'record.someRate': '{games} delas contam.',
  'record.agrees': 'Este navegador chegou a {reached} — o mesmo número que esta página.',
  'record.disagrees':
    'Este navegador chegou a {reached} e esta página diz {shown}. Se não coincidem, é esta página que está errada.',
  'record.leftOutUnsigned': '{count} ainda não assinadas pelos dois jogadores',
  'record.leftOutInvalid': '{count} não se verificam',
  'record.leftOut': 'Ficaram de fora: {detail}.',
  'record.empty': 'Ainda não há partidas assinadas nesta carteira.',
  'record.emptyNote':
    'Isso não é bom nem mau sinal — é uma carteira sem histórico. Jogue uma partida e assine o resultado.',
  'record.everyGame': 'Todas as partidas, pela ordem em que contam',
  'record.won': 'Ganha',
  'record.lost': 'Perdida',
  'record.drew': 'Empate',
  'record.casual': 'Amigável — nunca conta',
  'record.tooShort': 'Menos de {moves} lances — registada, não conta',
  'record.farmed': 'Partidas a mais contra este adversário — já não mexe em nenhum dos ratings',
  'record.gameLine': '{termination} · {moves} lances · bloco {block}',
  'record.footer':
    'Todos os números aqui derivam de assinaturas feitas pelos dois jogadores. Ninguém os pode editar — nem a pessoa de quem falam, nem nós.',

  'judge.best': 'Melhor lance',
  'judge.bests': 'melhores lances',
  'judge.good': 'Bom',
  'judge.goods': 'bons lances',
  'judge.inaccuracy': 'Imprecisão',
  'judge.inaccuracies': 'imprecisões',
  'judge.mistake': 'Erro',
  'judge.mistakes': 'erros',
  'judge.blunder': 'Erro grave',
  'judge.blunders': 'erros graves',

  'study.title': 'Estudar uma partida',
  'study.note':
    'Cole uma partida em PGN — do Lichess, do Chess.com, de um torneio, de onde for — ou estude a que acabou de jogar. Aqui não se assina nada e nada mexe no seu rating.',
  'study.handedNote':
    'A partida que acabou de jogar. Aqui não se assina nada e nada mexe no seu rating — isto é para ver.',
  'study.pasteLabel': 'Cole uma partida em PGN',
  'study.open': 'Abrir',
  'study.analyse': 'Analisar esta partida',
  'study.looking': 'A percorrer a partida…',
  'study.lookingProgress': 'A percorrer a partida… {done} de {total} lances.',
  'study.wasBest': '{number} {san} — o melhor lance aqui.',
  'study.wasGood': '{number} {san} — um bom lance.',
  'study.wasWorse': '{number} {san} — {label}. {better} era melhor, por {lost} pontos de hipótese de vitória.',
  'study.acpl': '{acpl} centipeões perdidos por lance',
  'study.whiteAhead': 'As brancas estão melhor — {percent} por cento',
  'study.blackAhead': 'As pretas estão melhor — {percent} por cento',
  'study.nothingToComplain': 'nada a apontar',
  'study.caveat':
    'Revista pelo motor próprio desta aplicação, a correr no seu dispositivo — nível de clube, não Stockfish. Encontra os erros graves de uma partida vulgar e não contraria um grande mestre.',
  'study.reviewed': 'A partida foi revista. Percorra-a para ver o julgamento de cada lance.',
  'study.analysisFailed': 'A análise parou: {detail}. A culpa é nossa — avise-nos, por favor.',
  'study.playersVs': '{white} contra {black}',
  'study.animported': 'Uma partida importada',
  'study.heading': '{players} · {moves} lances',
  'study.loaded': '{plies} lances carregados. Percorra-os com as setas.',

  'cert.title': 'Uma partida assinada',
  'cert.fetching': 'A obter a partida…',
  'cert.stillPlaying': 'Essa partida ainda está a decorrer. O certificado aparece quando ela terminar.',
  'cert.unreconstructable': 'Essa partida não pode ser reconstruída, por isso aqui não há nada para verificar.',
  'cert.onlyOne': 'Por agora só um jogador assinou. Passa a registo quando os dois o tiverem feito.',
  'cert.verified':
    'Os dois jogadores assinaram este resultado, e este navegador acabou de verificar as duas assinaturas.',
  'cert.bad': 'Estas assinaturas não batem certo. Não acredite neste resultado.',
  'cert.nothingAsked':
    'Não foi pedido nada ao nosso servidor para chegar a essa conclusão além da própria partida — as assinaturas foram verificadas aqui, no seu dispositivo, contra o texto exato que os dois jogadores assinaram.',
  'cert.checkFailed': 'A verificação falhou: {reason}.',
  'cert.unknown': 'desconhecido',
  'cert.winnersRecord': 'Ver o histórico do vencedor',
  'cert.playYourself': 'Jogue você uma partida',
  'cert.signed': 'assinada',
  'cert.notSignedYet': 'ainda não assinada',

  'certificate.abandoned': 'Abandonada',
  'certificate.cannotDraw': 'Este navegador não consegue desenhar um certificado.',
  'certificate.noPicture': 'Não foi possível criar a imagem.',
  'certificate.whiteWins': 'Ganham as brancas',
  'certificate.blackWins': 'Ganham as pretas',
  'certificate.drawn': 'Empate',
  'certificate.rated': 'a contar',
  'certificate.casual': 'amigável',
  'certificate.summary': '{reason} · {moves} lances · {kind}',
  'certificate.bothSigned': 'Os dois jogadores assinaram este resultado',
  'certificate.evidence':
    'Bloco Nimiq {block} · partida {game}… · qualquer pessoa pode verificar em {where}',
  'certificate.signatureOf': 'Assinatura de {side}',
  'certificate.tagline': 'Um rating que ninguém emitiu e ninguém pode revogar.',

  'share.asPicture': 'Partilhar como imagem',
  'share.asPgn': 'Guardar como PGN',
  'share.sent': 'Enviado.',
  'share.savedPicture': 'Guardado como imagem.',
  'share.savedPgn': 'Guardado como PGN, que todos os programas de xadrez leem.',
  'share.notOnDevice': 'Essa partida já não está neste dispositivo.',
  'share.didNotWork': 'Isso não funcionou neste dispositivo. A partida está segura de qualquer forma.',

  'sign.notOver': 'Essa partida ainda não terminou.',
  'sign.syncing':
    'O Nimiq Pay ainda está a pôr-se em dia com a cadeia. Dê-lhe alguns segundos e assine outra vez.',
  'sign.noHeight':
    'O Nimiq Pay não conseguiu ler a altura da cadeia agora mesmo, e uma partida precisa de uma para ser ordenada. Tente daqui a pouco.',
  'sign.notYourGame': 'Esta carteira não jogou essa partida, por isso não há aqui nada para ela assinar.',

  'api.offline': 'Não foi possível chegar à partida. Verifique a ligação.',
  'api.something': 'Alguma coisa correu mal.',
  'api.badShape':
    'O servidor enviou algo que esta aplicação não conseguiu ler. A culpa é nossa, não sua — a sua partida está segura no servidor.',
  'poolApi.offline': 'Não foi possível chegar ao fundo.',
  'poolApi.refused': 'Não foi possível fazer essa reclamação.',
  'poolApi.alreadyClaimed': 'Já reclamou hoje. O problema muda à meia-noite, e isto também.',
  'poolApi.deviceClaimed':
    'Este dispositivo já reclamou hoje — um por dispositivo, que é o que impede um script de esvaziar o fundo.',
  'poolApi.notFunded':
    'O fundo não tem dinheiro neste momento, por isso não há nada para reclamar. Resolver continua a contar para a sua sequência.',
  'poolApi.needsNimiqPay':
    'Reclamar precisa do Nimiq Pay, que é o que diz ao fundo que duas reclamações vêm de duas pessoas diferentes.',
  'poolApi.unreachable':
    'Não foi possível chegar ao fundo. A sua solução está segura — tente reclamar outra vez daqui a pouco.',

  'send.needsNimiqPay': 'Enviar NIM acontece na aplicação Nimiq Pay. Abra isto por lá.',
  'send.memoTooLong': 'Essa mensagem é demasiado longa para uma transação Nimiq. A culpa é nossa.',
  'send.badAmount': 'Esse não é um valor que se possa enviar.',
  'send.waiting': 'À espera da sua carteira',
  'send.declined': 'Não foi enviado nada. Os seus NIM estão onde estavam.',
  'send.failed': 'Não foi possível enviar. Não saiu nada da sua carteira.',
  'send.tip': 'Envie-lhe {amount} NIM',
  'send.tipTitle': 'Boa partida?',
  'send.tipNote':
    'Envie-lhe NIM diretamente da sua carteira. Não passam por nós, e a transação diz de que partida se trata.',
  'send.tipSent': 'Enviado. {amount} NIM foram da sua carteira para a dele.',
  'send.poolTitle': 'Devolva alguma coisa',
  'send.poolNote':
    'O fundo paga a um desconhecido por resolver o problema do dia. Qualquer pessoa pode acrescentar, e cada pagamento que faz está na cadeia com o problema lá escrito.',
  'send.poolAdd': 'Juntar {amount} NIM ao fundo',
  'send.poolSent': 'Enviado. {amount} NIM estão no fundo para quem resolver a seguir.',
  'send.sending': 'À espera da sua carteira…',

  'app.broke': 'Alguma coisa se partiu',

  /* ---------------------------------------------------------------- the portable record */
  'record.take': 'Leva o teu hist\u00f3rico contigo',
  'record.takeNote':
    'Um ficheiro com cada partida e cada s\u00e9rie de problemas assinadas neste dispositivo. Qualquer pessoa pode verific\u00e1-lo sem este site e sem nos perguntar nada.',
  'record.takeButton': 'Guardar o meu hist\u00f3rico',
  'record.takeEmpty': 'Ainda n\u00e3o h\u00e1 nada assinado neste dispositivo.',
  'record.recordSent': 'Enviado \u2014 {games} partidas e {runs} s\u00e9ries de problemas.',
  'record.recordSaved': 'Guardado \u2014 {games} partidas e {runs} s\u00e9ries de problemas.',
  'record.recordSkipped': '{count} de fora: n\u00e3o assinadas por ambos os lados, ou da outra rede.',

  /* ---------------------------------------------------------------- the verify screen */
  'verify.title': 'Verificar um hist\u00f3rico',
  'verify.intro':
    'Algu\u00e9m te enviou um hist\u00f3rico Scoresheet? Abre-o aqui. O teu navegador verifica cada assinatura e calcula a pontua\u00e7\u00e3o sozinho. Nada \u00e9 enviado, e esta p\u00e1gina n\u00e3o precisa do nosso servidor.',
  'verify.choose': 'Escolher um ficheiro',
  'verify.checking': 'A verificar cada assinatura\u2026',
  'verify.unreadable': 'N\u00e3o foi poss\u00edvel ler esse ficheiro.',
  'verify.notARecord': 'Isso n\u00e3o \u00e9 um hist\u00f3rico Scoresheet.',
  'verify.oneGame': '1 partida verificada, e {runs} s\u00e9ries de problemas.',
  'verify.manyGames': '{games} partidas verificadas, e {runs} s\u00e9ries de problemas.',
  'verify.rating': 'Pontua\u00e7\u00e3o {rating}, de {games} partidas pontuadas contra {opponents} pessoas diferentes.',
  'verify.noneRate': 'Nenhuma destas partidas pontua, por isso n\u00e3o h\u00e1 pontua\u00e7\u00e3o para verificar.',
  'verify.provisional': 'Provis\u00f3ria: uma pontua\u00e7\u00e3o assenta ap\u00f3s dez advers\u00e1rios diferentes.',
  'verify.puzzleRating': 'Pontua\u00e7\u00e3o de problemas {rating}.',
  'verify.findings': 'O que n\u00e3o bateu certo',
  'verify.badSignature': 'Partida {id}: a assinatura de {side} n\u00e3o corresponde.',
  'verify.notTheirs': 'Foi deixada de fora uma partida que pertence a outra pessoa.',
  'verify.wrongChain': 'Foi deixada de fora uma partida da outra rede.',
  'verify.malformed': 'N\u00e3o foi poss\u00edvel ler um registo: {detail}',
  'verify.gameRootMismatch': 'As partidas n\u00e3o d\u00e3o a impress\u00e3o digital que este hist\u00f3rico declara. Algo foi acrescentado ou retirado depois.',
  'verify.runRootMismatch': 'As s\u00e9ries de problemas n\u00e3o d\u00e3o a impress\u00e3o digital que este hist\u00f3rico declara.',
  'verify.anchorBefore': 'Este hist\u00f3rico diz ter sido selado na cadeia antes de uma das suas pr\u00f3prias partidas.',
  'verify.anchored': 'Selado na cadeia Nimiq, depois da \u00faltima partida que cont\u00e9m.',
  'verify.caveat':
    'Isto prova que estas partidas aconteceram e n\u00e3o foram alteradas. N\u00e3o prova que a lista est\u00e1 completa \u2014 qualquer pessoa pode omitir uma derrota de um hist\u00f3rico que publica ela pr\u00f3pria.',

  'study.tryAgain': 'Tenta tu',
  'study.tryGiveUp': 'Mostra-me',
  'study.tryPrompt': '\u00c9 a tua vez. Encontra algo melhor do que jogaste.',
  'study.tryThinking': 'A analisar\u2026',
  'study.tryFound': '{san} \u2014 \u00e9 isso. Era o que o motor queria.',
  'study.tryBetter': '{san} \u00e9 melhor do que o que jogaste, mas n\u00e3o \u00e9 o melhor. Custa {lost} pontos em vez disso.',
  'study.tryNo': '{san} custa {lost} pontos \u2014 n\u00e3o \u00e9 melhor do que a tua jogada. Tenta outra.',
  'study.tryUnknown': 'O motor n\u00e3o respondeu a tempo, por isso esta fica por julgar.',

  'study.trainThis': 'Treinar isto',
  'study.trainChecking': 'A verificar se isto dá um problema justo…',
  'study.trainAdded': 'Adicionado ao teu treino. Vais voltar a ver esta posição.',
  'study.trainAlready': 'Esta já está no teu treino.',
  'study.trainNotUnique': 'Não adicionado: aqui há mais do que uma boa jogada, não seria um problema justo.',
  'study.trainNotSuitable': 'Não adicionado: a melhor jogada aqui não é algo que um problema possa pedir.',
  'study.trainNotSound': 'Não adicionado: um olhar mais longo não concordou com o primeiro.',
  'study.trainUnknown': 'O motor não respondeu a tempo, por isso não foi adicionado.',
  'puzzles.mine': 'Os teus próprios erros',
  'puzzles.mineDetail': '{count} à espera. Posições que erraste, as piores primeiro.',
  'puzzles.mineDone': 'São todos. Trabalhaste todos os erros que guardaste.',

  /* ---------------------------------------------------------------- tournaments */
  'lobby.tourneyTitle': 'Organizar um torneio',
  'lobby.tourneyNote': 'Todos contra todos, ou suíço acima de oito. Você recebe um link para enviar aos jogadores.',
  'lobby.seats': 'Jogadores',
  'lobby.seats4': 'Quatro',
  'lobby.seats4Detail': 'Seis partidas, uma rodada cada',
  'lobby.seats6': 'Seis',
  'lobby.seats6Detail': 'Quinze partidas',
  'lobby.seats8': 'Oito',
  'lobby.seats8Detail': 'Todos contra todos',
  'lobby.seats12': 'Doze',
  'lobby.seats12Detail': 'Suíço, cinco rodadas',
  'lobby.hold': 'Organizar um torneio',
  'lobby.tourneyName': 'Torneio',
  'tourney.title': 'Torneio',
  'tourney.loading': 'A carregar o torneio\u2026',
  'tourney.notFound': 'N\u00e3o h\u00e1 nenhum torneio com essa liga\u00e7\u00e3o.',
  'tourney.unavailable': 'Esse torneio n\u00e3o p\u00f4de ser carregado agora.',
  'tourney.open': 'Aberto \u2014 {entrants} de {seats} lugares ocupados.',
  'tourney.running': 'A decorrer \u2014 {entrants} jogadores.',
  'tourney.finished': 'Terminado \u2014 {entrants} jogadores.',
  'tourney.agrees': 'Este navegador calculou a tabela sozinho, a partir das partidas, e chegou \u00e0 mesma ordem.',
  'tourney.disagrees': 'Este navegador chega a outra tabela com estas partidas. Algo n\u00e3o bate certo.',
  'tourney.standings': 'Classifica\u00e7\u00e3o',
  'tourney.games': 'Partidas',
  'tourney.round': 'Ronda {round}',
  'tourney.toPlay': 'por jogar',
  'tourney.prize': '{nim} NIM',
  'tourney.caveat': 'Cada partida acima foi conferida neste navegador, contra as duas assinaturas nela. A ordem decorre dessas partidas, e você acabou de ver o cálculo.',
  'tourney.agreesSigned': 'Este navegador conferiu sozinho as {games} partidas assinadas e chegou à mesma tabela, sem nos perguntar nada.',
  'tourney.dropped': '{games} partidas enviadas não puderam ser conferidas e ficaram fora da tabela.',
  'tourney.caveatUnchecked': 'A ordem decorre destes resultados, e você acabou de conferir isso. Se estes são os resultados é outra questão, e cada partida a responde no seu próprio certificado.',
  'tourney.join': 'Entrar neste torneio',
  'tourney.joinFailed': 'Não deu certo. As vagas podem ter acabado.',
  'tourney.yours': 'Suas partidas',
  'tourney.playThem': 'ainda não jogada',
  'tourney.report': 'Enviar a partida',
  'tourney.reportFailed': 'Essa partida não foi aceita. Ela precisa estar assinada por vocês dois.',
  'tourney.back': 'Voltar',
};
